### ISSUE TITLE
flask db upgrade fails

### ISSUE THREAD

**Issue by ralphte** [hashview/hashview#108]
when the command `flask db upgrade` is run, I get the following error

```
isqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1045 (28000): Access denied for user 'hashview'@'172.28.0.1' (using password: YES)
(Background on this error at: https://sqlalche.me/e/20/f405)
```
I have validated the username and password, and permissions for the database `hashview` and they are all correct. The password is set to  `hashview`, so it has no complexity. Finally, when I run the app, I get the following error showing that the flask application can talk to the database, but the database is empty.

```
sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'hashview.users' doesn't exist
[SQL: SELECT users.password AS users_password 
FROM users 
WHERE users.id = %(id_1)s 
 LIMIT %(param_1)s]
[parameters: {'id_1': 1, 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

**Comment by i128** [comment]
Same issue as this: https://github.com/hashview/hashview/issues/109
Will be fixed in next release.
