### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by i128** [hashview/hashview#11]
The ability to perform Hash, Username, password searches via API

Need to figure out if we want to require user auth for this or not

**Comment by i128** [comment]
Moving this to v0.8.2 since id like to wrap this into a larger release focused on user level api calls.

**Comment by i128** [comment]
Add ability for end user to register API key. Key should be stored as a user attribute in db. sent as header from clients. Checked at each route request.

**Comment by bandrel** [comment]
In addition to being able to search via API, I'd like the ability to directly seed the insta-crack db with new hash:clears combos

**Comment by i128** [comment]
Seeding databases via api wont be implemented with this release. 
As it stand we run the risk of 1) over filling the db and causing performance issues. This happened with the ruby version of the project 2) we dont do any validation on importing of cracked hashes from the agent. I dont want to make this process easier until validation checks are in place.
