### ISSUE TITLE
Running jobs get deleted

### ISSUE THREAD

**Issue by vanjobanjo** [hashview/hashview#112]
Hi,
we are running hashview v0.8.0 with a single agent. Server and agent run on the same host. Recently, the problem has emerged that all jobs, both running and completed, are deleted within a few minutes of starting a new job. However, the results and password analyses can still be retrieved under /analytics. 

The problem first occurred during a job that had already been running for more than 18 hours. Since then, every new job terminates after about 10 minutes and is automatically deleted.

The agent log records a "Terminated" by hashcat when the server deletes the job. The server itself, even in debug mode, only logs the agent's heartbeat, no errors.

We also tried to create a job without starting it. Interestingly, this job wasn't deleted.
Up until now, everything ran smoothly - any ideas where the problem could come from?

**system info**
|                 os               |    python  | hashview | hashcat |
| -------------------- | --------- | --------- | -------- |
| Ubuntu 18.04.6 LTS |      3.7.5    |   v0.8.0    |    v6.2.6 |

**steps to reproduce the behaviour:**
1. configure a new job
2. start the job
3. wait ~10 minutes
4. refresh the page
&rarr; job is gone

**hashcat output (hashview agent log)**
`[s]tatus [p]ause [b]ypass [c]heckpoint [f]inish [q]uit => Terminated`

**hashview log around the time the job gets deleted (everything looks normal)**
```
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:00:38] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:00:48] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:00:58] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:01:08] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:01:18] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:01:28] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:01:38] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:01:48] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:01:58] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
INFO  [werkzeug] 127.0.0.1 - - [17/Aug/2023 17:02:08] "POST /v1/agents/heartbeat HTTP/1.1" 200 -
```

**Comment by i128** [comment]
To confirm, when you're reproducing the error, on step 4, are you refreshing the homepage, or the jobs page?

**Comment by vanjobanjo** [comment]
The data retention value is 0:

```
+----+------------------+
| id | retention_period |
+----+------------------+
|  1 |                0 |
+----+------------------+
```

**Comment by i128** [comment]
Ah, i think thats the issue. The data retention thread, reads that value in the db. Checks the current date vs date of when the job was created and if the difference is greater than the retention period, will delete the job.

Set the data retention period value to something between 1 and 65535.

I thought i had put in an exception so that if the user set it to 0 it would disable retention, but i dont see that being the case.

That said im 99% sure thats the issue.

**Comment by vanjobanjo** [comment]
Thanks, we'll try that. Though we've always had retention to 0 and it's never been an issue 🤔

**Comment by vanjobanjo** [comment]
Setting the retention period to a higher value fixed it, thanks!
