### ISSUE TITLE
Domain Controller Dump Parser

### ISSUE THREAD

**Issue by MrJester** [hashview/hashview#144]
HashView should parse the hash file before reading it with hashcat to parse out usernames. Using common tools (ntdsextract) to dump password hashes from a Domain Controller gives us 

USERNAME:NT HASH

should be able to parse these to put into the database before cracking them with hashcat. This makes the process of attributing the username to the password easier.

**Comment by i128** [comment]
For self reference:
Example Formats:

v1.0
Password hashes:
    Administrator:$NT$0817033191709a45c93baa986d933d0e:::
Password history:
    Administrator_nthistory0:$NT$0817033191709a45c93baa986d933d0e:::
    Administrator_nthistory1:$NT$70aa17fabbaf3b0511f430844c6de431:::
    Administrator_lmhistory0:f8eab0fa471aff3edab057c59e5d0aa5:::

v1.2 (designed for JtR
name:$NT$2e8fc4b95229a6ea67b1f69d04ee4000:::
name:e4c2436ddd1f655c6eedd0fa5525f000:::


Maybe consider only supporting v1.3

**Comment by i128** [comment]
This feature was just added to the dev branch. I dont have a large data set to test with so it may be buggy, but if you want to give it a spin, let me know if you encounter any issues

**Comment by MrJester** [comment]
So I'm using this command with the latest 1.3 version of 

"dsusers.py ntds.dit.export/datatable.3 ntds.dit.export/link_table.4 dump_stuff --syshive system --passwordhashes --lmoutfile lm-out.txt --ntoutfile nt-out.txt --pwdformat ocl"

Taking the nt.out file which is in the format

<USERNAME>:<HASH>

Hashview reads it in and I manually specify type 1000 but it does nto parse the line before passing it to hashcat. This in turn will not crack. Did I perform the steps incorrectly?

**Comment by i128** [comment]
All of the examples I could find looked like the format was 
name:$NT$2e8fc4b95229a6ea67b1f69d04ee4000:::
name:e4c2436ddd1f655c6eedd0fa5525f000:::

I'm guessing the --pwdformat ocl is what switches it to 
username:hash

I just created a test branch called dsusers. In it, i changed the parser to look for the single colon. If you are willing, could you check that out and see if that works for you?

**Comment by i128** [comment]
Feature added in release v0.4-beta
