### ISSUE TITLE
Support distributed cracking

### ISSUE THREAD

**Issue by ccammilleri** [hashview/hashview#192]
distributed support is on the roadmap, but +1 this issue if you'd like to see it expedited.

**Comment by phillips321** [comment]
+1 for distributed cluster support.

**Comment by yashar6909** [comment]
+1 :)

**Comment by ccammilleri** [comment]
This is actively being worked on. We had to re engineer some backend job handling to help with future plans we have with this project. 

A couple engineering notes:

1. There will be a agent worker that can be deployed anywhere. Agents will connect to a master instance.
2. Resque workers will no longer work for agents and will have to move to an restful API model. Reasons: mysql and redis shouldn't be shared with untrusted workers. basically; security reasons.

**Comment by altkdub** [comment]
+1 for distributed cluster support

**Comment by H8to** [comment]
+1 on this feature

**Comment by gtrdlr** [comment]
+1

**Comment by ccammilleri** [comment]
Feels good to say this has finally landed! hoorah!
