### ISSUE TITLE
Email Settings

### ISSUE THREAD

**Issue by recrudesce** [hashview/hashview#202]
When using Hashview in AWS and via SES, you need to provide a FROM address, as the SMTP username is not the same as the domains added to SES.

Can we have an option to define the FROM address ?

Thanks :)

**Comment by ccammilleri** [comment]
I dont see why not, sounds like a legit need. We'll add it to the todos.

**Comment by i128** [comment]
Issue should now be resolved.

Do a 
`git pull`

To get the latest code, and then run the upgrade instructions found here:

https://github.com/hashview/hashview/wiki/Upgrading-Hashview
