### ISSUE TITLE
Installing onto Amazon AMI (and I presume CentOS as well)

### ISSUE THREAD

**Issue by recrudesce** [hashview/hashview#205]
So, I didn't install hashview onto a Debian box, so apt-get didn't exist etc etc.  I installed onto an Amazon AMI, which has an OS based on CentOS and uses yum.

So, here's the issues I found, and here's how to overcome them !

>sudo apt-get update
>sudo apt-get install mysql-server libmysqlclient-dev redis-server openssl rake
>[optional, but recommended]
>mysql_secure_installation

OK, so libmysqlclient-dev doesn't exist, nor does redis-server.  The first one is easy to fix, you just need to `yum install mysql-devel.noarch`.  Second one is a little more complex - you need to download and run the script from https://gist.github.com/khelll/ff9461bfda8ebfdc488e (make sure you edit the `version=3.2.0` line to be `version=3.2.8` to get the latest version)

mysql_secure_installation will FAIL because it'll ask you for a root password, which you've not set up yet, so you need to start mysqld first via `sudo service mysqld start` and set a password via `/usr/libexec/mysql55/mysqladmin -u root password 'newpassword'`
Then you can run `mysql_secure_installation` and enter the password you just set

my.cnf is in `/etc/my.cnf` not the location shown in the installation instructions.

USAGE:
Other issues, the Setup asks you for the hashcat path, when actually it wants the binary name as well (ie not just the path).  If you just put `/opt/hashcat-3.30` in the box it'll fail to crack anything, you specifically have to put the binary name at the end of the path e.g. `/opt/hashcat-3.30/hashcat64.bin`

Hope this helps :)

**Comment by ccammilleri** [comment]
@recrudesce this is great stuff! Thanks for documenting. I foresee a need to modify the installation wiki to support non-deb installs. Sheesh, didn't know you had to manually install redis on centos.

TODO: refactor the installation wiki so this fits in seamlessly

**Comment by recrudesce** [comment]
> Sheesh, didn't know you had to manually install redis on centos.
You def do on Amazon AMI Linux, not totally sure about CentOS - it might be in the CentOS repos ?

**Comment by ccammilleri** [comment]
added a link in the wiki to here. We'll add this info to the wiki at some point.
