### ISSUE TITLE
Masking or removing plaintext passwords

### ISSUE THREAD

**Issue by nebriv** [hashview/hashview#211]
It'd be nifty to have a global or customer option to mask passwords ( P@ssw0rd -> usllldll) instead of printing plain text, or storing in plain text within the DB. Another option could be to just remove any masking and the password all together and just mark a user as cracked - potentially storing the plaintext in a separate table for analytics depending on paranoia levels.

This could be useful for corporate implementations where it may not be desirable to associate the cracked password with the user. Any idea if this would be feasible (& easily implemented) or desired? I'm going to poke around and see what I can hack together, but I'm not much of a ruby dev.

**Comment by i128** [comment]
Masking the display of plaintext passwords to the front end should be possible, but doing it on the backend would render the analytics portion useless.  We've toyed with the idea of encrypting the db as a workaround.

**Comment by ccammilleri** [comment]
Thanks for the suggestion, but at this time we've decided not to prioritize this feature. I really like the idea, but certain level of trust must be established with security staff if (given) a company hash dump. If stolen, well, you have other issues.

As loose workaround, I'd suggest decoupling usernames from hashes.
