### ISSUE TITLE
500 error on large wordlist upload

### ISSUE THREAD

**Issue by binarytraveler** [hashview/hashview#248]
I have several large wordlists ... the largest is almost 17 Gig in flat txt.. Useful for policies over 14 characters in corp settings and WPA cracking.

While attempting to upload... the file seems to make it successfully, but post processing fails after a few minutes.  Looks like an out of memory error with Sinatra....

https://1.1.1.1:4567/wordlists/list -> /wordlists/add
2017-03-11 13:04:20 - NoMemoryError - failed to allocate memory:
        /home/administrator/hashview/routes/wordlists.rb:55:in `block (2 levels) in <top (required)>'
        /home/administrator/hashview/routes/wordlists.rb:55:in `open'
        /home/administrator/hashview/routes/wordlists.rb:55:in `block in <top (required)>'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:225:in `context'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/session/abstract/id.rb:220:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/logger.rb:15:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/commonlogger.rb:33:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/methodoverride.rb:22:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /home/administrator/.rvm/gems/ruby-2.2.2/gems/rack-1.6.5/lib/rack/handler/webrick.rb:88:in `service'
        /home/administrator/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
        /home/administrator/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
        /home/administrator/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
1.1.1.2 - - [11/Mar/2017:13:04:20 -0700] "POST /wordlists/upload/ HTTP/1.1" 500 30 0.3712
1.1.1.2 - - [11/Mar/2017:12:58:19 MST] "POST /wordlists/upload/ HTTP/1.1" 500 30
https://1.1.1.1:4567/wordlists/add -> /wordlists/upload/

**Comment by i128** [comment]
As it stands the wordlist is loaded into memory before being imported to the FS. A work around is being developed and is slated for v0.6 wherein you SCP the wordlist to a directory and the app will auto-import it for you.

**Comment by i128** [comment]
Issue should now be resolved.

Do a 
`git pull`

To get the latest code, and then run the upgrade instructions found here:

https://github.com/hashview/hashview/wiki/Upgrading-Hashview
