### ISSUE TITLE
Bug in Combo Attack

### ISSUE THREAD

**Issue by binarytraveler** [hashview/hashview#250]
small bug in command line arguments being passed in combo attack:

hashcat64.bin -m 1000 --potfile-disable --status-timer=15--outfile-format 3  --outfile 

gives error about hashcat usage... needs a space between --status-timer and --outfile-format

hashcat64.bin -m 1000 --potfile-disable --status-timer=15 --outfile-format 3  --outfile

**Comment by binarytraveler** [comment]
adding space to line in hashview/helpers/build_crack_cmd.rb to fix:

elsif attackmode == 'combinator'
      cmd = hcbinpath + ' -m ' + hashtype + ' --potfile-disable' + ' --status-timer=15' + ' --outfile-format 3 ' + ' --outfile ' + crack_file + ' ' + ' -a 1 ' + target_file + ' ' + wordlist_one.path + ' ' + ' ' + wordlist_
two.path + ' ' + @task.hc_rule.to_s + ' -w 3'

**Comment by i128** [comment]
Issue should now be resolved.

Do a 
`git pull`

To get the latest code, and then run the upgrade instructions found here:

https://github.com/hashview/hashview/wiki/Upgrading-Hashview
