### ISSUE TITLE
Jobs Fail to Start

### ISSUE THREAD

**Issue by i128** [hashview/hashview#264]
**Issue Detail:** 
After starting Hashview, jobs can be created, queued and stopped, but when started, no crack job is run. Viewing the output of the foreman job, hearbeats from the local agent are not seen.

**Issue Cause:**
This issue can be caused if there are stale threads that didn't clean out properly. To check:

1. Stop the hashview proccess
2. Identify all remaining stale resque proccesses (ps -ef | grep -i resque)
3. If you see any listed resque proccesses, you're affected

**Workaround & Fixes**

1. kill all stale process resque procceses
2. restart redis (sudo /etc/init.d/redis-server restart)
3. Start hashview (twice?)

**or**

1. Restart your hashview server.

**Affected Versions**
Starting with version v.0.6.0

**Comment by ccammilleri** [comment]
closing b/c this issue only reveals itself rarely and under extreme starting and stopping which only developers might be doing.

I've moved this information into the troubleshooting wiki page.

**Comment by i128** [comment]
Still and issue.

**Comment by hegusung** [comment]
Reinstalled and it worked well, don't know what caused this

**Comment by i128** [comment]
Closing, let me know if this comes back up.
