### ISSUE TITLE
Job Status Doesn't Populate

### ISSUE THREAD

**Issue by nvoss** [hashview/hashview#268]
We are attempting to crack NTLM hashes, the job is running tasks, but the job status never updates.

![image](https://cloud.githubusercontent.com/assets/6876960/24222381/db742e6a-0f1f-11e7-9864-b17d94fc1653.png)

**Comment by i128** [comment]
What is the output of following cmd on the server running hashview
`ps -ef | grep hashcat`

**Comment by nvoss** [comment]
![image](https://cloud.githubusercontent.com/assets/6876960/24251537/76f8e4ec-0fa8-11e7-8d71-aede9bcf82f2.png)

**Comment by i128** [comment]
Okay, two things to check.
1) on a new terminal, type the following to see if there's any output
`cat /home/lucy/hashview/control/outfiles/hcoutput_33.txt`

2) If there's output, go to the terminal running the rake task and type the letter "s". Then wait about 15-30 seconds for the homepage to refresh and you should see a status.  

Let me know if either of those work or not.

**Comment by nicbrink** [comment]
I think this is fixed with the new code.  The --status parameter was added in the build_crack_cmd.rb file.

**Comment by i128** [comment]
Agreed. This should be fixed in v0.6.0.1

**Comment by nvoss** [comment]
It did work, but wasn't updating automatically.  I'll upgrade to v0.6.0.1 and try that.
