### ISSUE TITLE
Errors in new install instructions - 0.6-beta

### ISSUE THREAD

**Issue by binarytraveler** [hashview/hashview#269]
adding a second box and going through the install notes from WIKI.

did a fresh git clone and everything worked fine up until running hashview.

RACK_ENV=production foreman start - results in "foreman: command not found"

gem install foreman - to install foreman (need to update bundle install list)

Running start now errors with the following:

RACK_ENV=production foreman start
ERROR: Procfile does not exist.

**Comment by i128** [comment]
Standby, v0.6.0 isnt quite out yet.

**Comment by i128** [comment]
Okay do a git pull (or wipe and git clone) and try again. You were pulling from the master branch which was at v0.5.1. I just changed it over to v0.6.0 so you should be able to try again. Let us know if you run into more problems.

**Comment by binarytraveler** [comment]
ok that worked much better.

Though the wordlist import does not appear to be working when you drop in file into the control/wordlists directory

**Comment by i128** [comment]
Few question: 
1) whats is the file extension of the wordlist (if any)
2) Do you see the following message periodically scroll by when you start the foreman command:
`background-worker.1 | resque-scheduler: [INFO] 2017-03-23T14:38:51-05:00: queueing WordlistImporter (do_wordlist_importer)`

**Comment by binarytraveler** [comment]
1 - .txt mostly ....and a couple of .dic and .lst

2 -
======================================
13:32:03 hashcat-worker.1    | {"status"=>200, "type"=>"Message", "msg"=>"OK"}
13:32:05 background-worker.1 | resque-scheduler: [INFO] 2017-03-23T13:32:05-06:00: queueing TestJob (do_test_job)
13:32:05 background-worker.1 | resque-scheduler: [INFO] 2017-03-23T13:32:05-06:00: queueing WordlistImporter (do_wordlist_importer)
13:32:07 background-worker.1 | resque-scheduler: [INFO] 2017-03-23T13:32:07-06:00: queueing TestJob (do_test_job)
13:32:07 background-worker.1 | resque-scheduler: [INFO] 2017-03-23T13:32:07-06:00: queueing WordlistImporter (do_wordlist_importer)
13:32:08 hashcat-worker.1    | HEARTBEETING

**Comment by binarytraveler** [comment]
ah just kicked in with a few dupes in the list

lemme retry this

**Comment by binarytraveler** [comment]
hmmm .. so dropping files into /control/wordlists or doing the normal upload method seem to result in duplicate wordlist entries in the UI... the wordlist however is still just the single file.
<img width="1101" alt="screen shot 2017-03-23 at 2 00 31 pm" src="https://cloud.githubusercontent.com/assets/26350706/24267873/4b20d1ee-0fd1-11e7-859e-8686098ae17b.png">

**Comment by i128** [comment]
Interesting, there should be a check to validate if the file is already entered into the wordlists tables before trying to import it again... let me take a look.

**Comment by i128** [comment]
Okay found the issue, working on a fix, will update when its been tested

**Comment by i128** [comment]
Okay fix has been pushed to master BUT in your state you need to fix a few things manually before using it
1) go to /control/wordlists/ and delete all the files
2) go to the DB
`mysql -u root -p <password>`
`use hashview #hashview_dev if you're running in dev mode`
Remove all stale entries  
`delete from wordlists` 

Once thats done, restart hashview and move your wordlists over.
one thing to note, any tasks that were assigned to your old wordlists will need to be deleted too, this should be done via the UI.  Let me know if this works or if you have any further problems. 

Thanks for testing!

**Comment by i128** [comment]
ALSO, forgot to mention, during the import, the sizes of the wordfiles will initially say 0, but its a lie.  we had to break out the word count function, so after a few minutes (depending on the size of your word files), the correct word count SHOULD show up

**Comment by binarytraveler** [comment]
Just a follow up... files dropped into control/wordlists are now properly importing.  However files that are uploaded are getting a duplicate entry.  one for the upload and one for the file existing in control/wordlists.

easier to just put stuff into the directory... but if you want to maintain the upload function
<img width="1162" alt="screen shot 2017-03-27 at 8 31 46 am" src="https://cloud.githubusercontent.com/assets/26350706/24361795/22cfff18-12c8-11e7-90cc-c0703268d288.png">
 you'll need to tweak it.

**Comment by Guilty-King** [comment]
Hey guys a noob here 
I been trying to deploy it on vps before messing with my actual rig for error and setup 
I have attached  a transcript would you mind pointing out my errors as am not able to view any webpage
[35.185.219.141_20170418122927.txt](https://github.com/hashview/hashview/files/927591/35.185.219.141_20170418122927.txt)

**Comment by i128** [comment]
Issue fixed in dev branch

**Comment by i128** [comment]
@Guilty-King the error messages you see can be ignored. what happens when you try starting hashview via the foreman cmd?

**Comment by Guilty-King** [comment]
@i128 ignoring that hashview named database is already created 
I have some more transcripts attached 
Hope this is helpful and 
Running command 
RACK_ENV=production foreman start
Starts and infinite loop
[35.185.219.141_20170418122927.txt](https://github.com/hashview/hashview/files/954640/35.185.219.141_20170418122927.txt)
[35.185.252.73_20170425152534.txt](https://github.com/hashview/hashview/files/954641/35.185.252.73_20170425152534.txt)

**Comment by i128** [comment]
as the error message indicates: you must define an environment:

RACK_ENV=production foreman start

https://github.com/hashview/hashview/wiki/02_Running-Hashview

**Comment by ccammilleri** [comment]
@i128 where do we stand on this. can it be closed?

**Comment by i128** [comment]
Multiple wordlists has been resolved in v0.6.1
