### ISSUE TITLE
Hashfile Format for NetNTLMv1/v2

### ISSUE THREAD

**Issue by binarytraveler** [hashview/hashview#273]
So normally I take the hashes from responder and such and flip into hashcat.

But to use hashview.. which hashfile format are you looking for cause currently (.06) none of the formats seem to work

**Comment by i128** [comment]
For the Hashfile format, select $hash. On the next screen it should properly detect NetNTLMv1 or v2.

**Comment by Commodore128** [comment]
I'm finding that NetNTLMv2 hashes are being recognized, but the NetNTLMv1 hashes aren't... hashview is stripping off the 'username' portion of the hash and then hashcat throws a line-length exception when the job is run.

**Comment by ccammilleri** [comment]
heh, we might have another bug with ntlmv2 in .6

If I upload a hashfile of just ntlmv2 formatted hashes, chose $hash, than select 5600 when creating a job, the hashes will crack successfully but they will not be reported so in hashview.

As a workaround, I manually monitored hashes in control/outfiles/hc_output_$JOBID* when running the job.

I haven't tshooted the issue yet. It might be related to output format being in hex, or an issue with the agent uploading cracks, or api importing cracks.

I'm increasing the priority of this in trello...

**Comment by i128** [comment]
Issue resolved in v0.6.1
