### ISSUE TITLE
Hashtype 132 Results in Code 500 Internal Server Error

### ISSUE THREAD

**Issue by nicbrink** [hashview/hashview#276]
I have two different hash types: MsSql2005 type 132 an MSSQL2012 Type 1731.
Here are two sample hashes from the hashcat page:

0x010018102152f8f28c8499d8ef263c53f8be369d799f931b2fbe

0x02000102030434ea1b17802fd95ea6316bd61d2c94622ca3812793e8fb1672487b5c904a45a31b2ab4a78890d563d2fcf5663e46fe797d71550494be50cf4915d3f4d55ec375

While on the "Confirm Hash Type" page "/customers/upload/verify_hashtype" if I enter 132 into the box "manualHash" and select submit I receive a 500 Internal Server Error response.  
If I type 1731 into the "manualHash" box and click submit it moves on to "Assign Tasks to Jobs page."

It does not appear to matter what type of hash is actually submitted, the error seems to occur when "132" is submitted as the hashtype.

**Comment by i128** [comment]
If you're willing, check out the dev branch and let me know if its works there.

**Comment by nicbrink** [comment]
So, I grabbed the development branch and tried it again.  If the hash has never been uploaded before and I set the type to 132 it works and allows me to complete the scheduling of the job.  However if the hash already exists in the db and you try and upload it, hasview will error out with code 500.  Attached are logs from 2 separate
[logs.txt](https://github.com/hashview/hashview/files/890733/logs.txt)
 attempts.

**Comment by i128** [comment]
the overlapping import issue should be fixed in v0.6.1 (still in beta)

**Comment by i128** [comment]
Issue resolved in v0.6.1

**Comment by nicbrink** [comment]
I pulled the new code and it works correctly.  Thank you!
