### ISSUE TITLE
How do I add an agent?

### ISSUE THREAD

**Issue by sagitzadik** [hashview/hashview#278]
I could not find a way to add an agent (linux / windows) via the web gui, so I suppose it is not implemented yet (although on your website it shows that agents are somewhat supported: http://www.hashview.io/images/screenshots/agents-list.png).
Is there a way to add agents?
If not, what should I implement in order to have agents on my hashview?
(I don't mind writing a python script that send a request to heartbeat endpoint and runs whatever it receives from it)

**Comment by ccammilleri** [comment]
you're right, distributed agents are not supported yet. I just happen to grab a screenshot that shows multiple agents from dev branch we are working on atm.  Sorry about that, I can see how its misleading.

hopefully a couple more weeks and we'll have something released for the brave to test out. follow the hashview-agent repo. once code lands in there we are ready for some beta testers
