### ISSUE TITLE
Mask List

### ISSUE THREAD

**Issue by gtrdlr** [hashview/hashview#279]
More of a feature add then a bug, but the ability to point to a file of masks rather than creating individual tasks for each individual mask would be very handy.  

I appreciate the effort you put into hashview.  thanks!

Nevermind -- I see someone beat me to the punch... I'll read first next time.. thanks!

**Comment by i128** [comment]
I like it!

The way we do it now is clunky and you're right loading a file would be much easier.

**Comment by ccammilleri** [comment]
dup 
see #247
