### ISSUE TITLE
Duplicate wordlists generated on import

### ISSUE THREAD

**Issue by ccammilleri** [hashview/hashview#281]
on dev branch I uploaded a wordlist and it generated 3 wordlists. This is probably b/c the wordlistimporter resque task is running too frequently and creates a race condition with the import route  ('/wordlist/upload').

Suggestions would be to dial down the wordlist importer to 5s, and either remove all database import function within the route and just let the resque task detected the newly upload wordlist OR have the route directly call the wordlistimporter resque task after saving the file to disk.

This also creates an issue with deleting wordlists since the first initial deletion of the same (file named path) is removed. Thus, not allowing you to remove the other 2.

**Comment by ccammilleri** [comment]
thinking about this more you'll save race conditions between file write and db write. one thought I had was to do the db write first, before saving file to disk. that will prevent the wordlist importer resque task from starting to work on a file that is actively being imported via ui.

**Comment by i128** [comment]
Issue fixed in dev

**Comment by i128** [comment]
Issue fixed in v0.6.1-beta
