### ISSUE TITLE
Internal Server Error when starting jobs

### ISSUE THREAD

**Issue by kafkaesqu3** [hashview/hashview#288]
When I create a new job and attempt to start it, I get an Internal Server Error. If I go back to the jobs list, it shows the job has been queued but it never starts. The error happens no matter what hashtype or task I select. 

```
May  5 09:45:27 gpucracker app-web@5400.service[1031]: 2017-05-05 09:45:27 - NoMethodError - undefined method path' for nil:NilClass:
May  5 09:45:27 gpucracker app-web@5400.service[1031]: #011/home/username/hashview/helpers/build_crack_cmd.rb:42:in buildCrackCmd'
May  5 09:45:27 gpucracker app-web@5400.service[1031]: #011/home/username/hashview/routes/jobs.rb:290:in block (2 levels) in <top (required)>'
May  5 09:45:27 gpucracker app-web@5400.service[1031]: #011/home/username/hashview/routes/jobs.rb:279:in each'
May  5 09:45:27 gpucracker app-web@5400.service[1031]: #011/home/username/hashview/routes/jobs.rb:279:in block in <top (required)>'
```

It would appear the cause of this is wordlist is null when building the hashcat commands:
```
if @task.hc_rule == 'none'
        cmd = hc_binpath + ' -m ' + hashtype + ' --potfile-disable' + ' --status --status-timer=15' + ' --outfile-format 5 ' + ' --outfile ' + crack_file + ' ' + target_file + ' ' + wordlist.path
      else
        cmd = hc_binpath + ' -m ' + hashtype + ' --potfile-disable' + ' --status --status-timer=15' + ' --outfile-format 5 ' + ' --outfile ' + crack_file + ' ' + ' -r ' + 'control/rules/' + @task.hc_rule + ' ' + target_file + ' ' + wordlist.path
```
I'm attempting to debug to find the cause, but I don't know a lot of ruby

Full error: /var/log/syslog: https://pastebin.com/raw/R1zK9Dkx

**Comment by nicbrink** [comment]
Is you Hashcat Binary Path set correctly in the Global Settings?
It should look similar to this:
/opt/hashcat/hashcat64.bin

**Comment by kafkaesqu3** [comment]
My hashcat binary is located in my home folder. I confirmed I can crack hashes with the same binary. 
I also tested with chmod 777 on my hashcat folder to see if it was a permissions issue, and the same error occured.

**Comment by i128** [comment]
It could be related to this issue here:

https://github.com/hashview/hashview/issues/264

try the recommended troubleshooting steps listed there.
With your job, are you assigning it a custom task, or one of the default tasks pre-packaged with the app. What happens if you try starting a job where the task is 'raw brute'? (i.e. no wordlists)

**Comment by kafkaesqu3** [comment]
Thanks for the advice. 
I deleted all the default tasks, and stopped getting the 500 error, but the jobs still weren't starting. 
I followed the steps in the troubleshooting tips and in #264, and everything appears to be working

**Comment by ccammilleri** [comment]
refer to #264
