### ISSUE TITLE
500 due to unexpected data - Graceful handling?

### ISSUE THREAD

**Issue by relaxedricky** [hashview/hashview#289]
I'm trying to import a 5Mb SHA1 hash file setup with $user:$hash. When selecting SHA1 as the hash type I always get an error 500 :/

Seems the hash file contained a few lines of data that weren't a hash and caused it to crap out.

Could this be handled with more grace?

**Comment by d1str0** [comment]
In the meantime, run it through hashcat manually really quick with --remove. Do a mash of ?d?d?d?d or something simple and fast. It'll parse the whole file and remove bad entries for you. Even ?dx10 runs in 30seconds on my machine for SHA1 (takes way longer to load the file than to run the attack.

**Comment by ccammilleri** [comment]
while we could use more graceful handling, a recently release has more robust hash importing that will hopefully avoid the errors in the first place.
