### ISSUE TITLE
Remote Agent

### ISSUE THREAD

**Issue by nicbrink** [hashview/hashview#292]
Testing out the hashview-agent pieces.  Getting this error when the remote agent tries to report its status to the hashview server.  The hashview server will return a 500 error, and the remote agent will quit.  Finally the job goes to finished.  It never runs for more then 10-15 seconds.

16:37:59 web.1               |  ~ (0.000346) SELECT `id`, `jobtask_id`, `job_id`, `updated_at`, `status`, `agent_id`, `command` FROM `taskqueues` WHERE `id` = 17 ORDER BY `id` LIMIT 1
16:37:59 web.1               |  ~ (0.000198) SELECT `id`, `name`, `src_ip`, `uuid`, `status`, `hc_status`, `heartbeat`, `benchmark`, `devices`, `cpu_count`, `gpu_count` FROM `agents` WHERE (`uuid` = 'fb414ba0-5931-403b-a6d4-e9aa02116ff6' AND NOT(`status` = 'Pending')) ORDER BY `id` LIMIT 1
16:37:59 web.1               | 2017-05-18 16:37:59 - NoMethodError - undefined method `status=' for nil:NilClass:
16:37:59 web.1               | 	/opt/hashview_remoteagent/helpers/status.rb:49:in `updateTaskqueueStatus'
16:37:59 web.1               | 	/opt/hashview_remoteagent/routes/api.rb:81:in `block in <top (required)>'

**Comment by ccammilleri** [comment]
@nicbrink I just ran into this bug mysql and i'm trying to debug it. By chance did this happen when you only had one task assigned to a job, and was it a job that didnt chunk?

I think it might have to do with logic that detects if its the last chunk in the task (which is used to set the status of the task to complete)

**Comment by ccammilleri** [comment]
@nicbrink I figured it out...just like i thought, when there is only one chunk set for a task, as soon as the agent took the chunk, set that status to 'running', my logic was flawed and it would set the whole task to completed since it thought there were no more 'queued' tasks. Than the agent would kill its current duties for that task.

i'll push the fix to 0.7-beta branch in a couple minutes. thanks for your help!

**Comment by nicbrink** [comment]
Just to update:
I did run RACK_ENV= rake db:upgrade and there was only 1 task assigned to my test job.

I went ahead an pulled the 0.7-beta branch and can confirm that this is working
