### ISSUE TITLE
0.7-beta Hashcat Binary Path

### ISSUE THREAD

**Issue by nicbrink** [hashview/hashview#295]
On an new install of 0.7-beta with a new database there is a problem with the "Hashcat Binary Path" setting on the "Settings" configuration page.  The issue first manifested itself when you try to run a brute force task, since it is the only task that requires the "Max Task Runtime" value to be set.  Hashcat would error out with this error:
07:47:51 web.1               | 2017-05-22 07:47:51 - TypeError - no implicit conversion of nil into String:
07:47:51 web.1               | 	/opt/hashview_0.7/helpers/build_crack_cmd.rb:62:in `+'

If you go to the Settings page and try to adjust the "Max Task Runtime" I recieve the following error:
08:28:04 web.1               | 2017-05-22 08:28:04 - TypeError - no implicit conversion of nil into String:
08:28:04 web.1               | 	/opt/hashview_0.7/routes/settings.rb:33:in `file?'

Tracing backwards this seems to be result of the change to the Settings page to gray out the Hashcat Binary Path.  If I modify the settings.rb file and change:
unless File.file?(params[:hc_binpath])
to
unless File.file?(params[:hc_binpath].to_s)

It seems to work.  However, I am not confident that this is the fix.

**Comment by i128** [comment]
Yes, good find. There's an issue with that and the --force flag too. I have plans on creating a branch fix for this at some point. Good find!

**Comment by i128** [comment]
It should also be noted this is not unique to v0.7.0, but v0.6.0 and v0.6.1 too

**Comment by i128** [comment]
@nicbrink what value are you setting your max task runtime too?

**Comment by nicbrink** [comment]
I change it based upon the job.  (A per task setting would be awsome!!) Its is almost always set between 86400-259200.

**Comment by ccammilleri** [comment]
fixed in 0.7 which landed today
