### ISSUE TITLE
Web port 4567 doesn't load on Ubuntu 16.04

### ISSUE THREAD

**Issue by ama21n** [hashview/hashview#301]
Forgive me if I've missed something, I believe I've followed all the install instructions, running on Ubuntu 16.04 x64.
Output of RACK_ENV and netstat commands below...

# RACK_ENV=production foreman start
17:09:09 redis.1             | started with pid 17591
17:09:09 mgmt-worker.1       | started with pid 17592
17:09:09 hashcat-worker.1    | started with pid 17596
17:09:09 background-worker.1 | started with pid 17598
17:09:09 web.1               | started with pid 17600
17:09:09 redis.1             | 17591:C 25 May 17:09:09.665 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
17:09:09 redis.1             | 17591:M 25 May 17:09:09.666 * Increased maximum number of open files to 10032 (it was originally set to 1024).
17:09:09 redis.1             |                 _._
17:09:09 redis.1             |            _.-``__ ''-._
17:09:09 redis.1             |       _.-``    `.  `_.  ''-._           Redis 3.0.6 (00000000/0) 64 bit
17:09:09 redis.1             |   .-`` .-```.  ```\/    _.,_ ''-._
17:09:09 redis.1             |  (    '      ,       .-`  | `,    )     Running in standalone mode
17:09:09 redis.1             |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
17:09:09 redis.1             |  |    `-._   `._    /     _.-'    |     PID: 17591
17:09:09 redis.1             |   `-._    `-._  `-./  _.-'    _.-'
17:09:09 redis.1             |  |`-._`-._    `-.__.-'    _.-'_.-'|
17:09:09 redis.1             |  |    `-._`-._        _.-'_.-'    |           http://redis.io
17:09:09 redis.1             |   `-._    `-._`-.__.-'_.-'    _.-'
17:09:09 redis.1             |  |`-._`-._    `-.__.-'    _.-'_.-'|
17:09:09 redis.1             |  |    `-._`-._        _.-'_.-'    |
17:09:09 redis.1             |   `-._    `-._`-.__.-'_.-'    _.-'
17:09:09 redis.1             |       `-._    `-.__.-'    _.-'
17:09:09 redis.1             |           `-._        _.-'
17:09:09 redis.1             |               `-.__.-'
17:09:09 redis.1             |
17:09:09 redis.1             | 17591:M 25 May 17:09:09.666 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
17:09:09 redis.1             | 17591:M 25 May 17:09:09.666 # Server started, Redis version 3.0.6
17:09:09 redis.1             | 17591:M 25 May 17:09:09.666 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
17:09:09 redis.1             | 17591:M 25 May 17:09:09.666 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
17:09:09 redis.1             | 17591:M 25 May 17:09:09.666 * DB loaded from disk: 0.000 seconds
17:09:09 redis.1             | 17591:M 25 May 17:09:09.666 * The server is now ready to accept connections on port 6379
17:09:10 background-worker.1 | resque-scheduler: [INFO] 2017-05-25T17:09:10+10:00: Starting
17:09:10 background-worker.1 | resque-scheduler: [INFO] 2017-05-25T17:09:10+10:00: Loading Schedule
17:09:10 background-worker.1 | resque-scheduler: [INFO] 2017-05-25T17:09:10+10:00: Scheduling do_test_job
17:09:11 web.1               | /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:40:in `check_anchors': regular expression should not contain ^: "^(?!\\/(login|register|logout|v1\\/))" (Mustermann::CompileError)
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:31:in `compile'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regexp_based.rb:19:in `initialize'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:25:in `initialize'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `new'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `block in new'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/equality_map.rb:39:in `fetch'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `new'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann.rb:67:in `new'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1638:in `compile'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1626:in `compile!'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1357:in `add_filter'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1345:in `before'
17:09:11 web.1               | 	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1923:in `block (2 levels) in delegate'
17:09:11 web.1               | 	from ./hashview.rb:30:in `<main>'
17:09:11 web.1               | APPLICATION VERSION: 0.6.1
17:09:11 web.1               | DB:VERSION 0.6.1
17:09:11 background-worker.1 | resque-scheduler: [INFO] 2017-05-25T17:09:11+10:00: Scheduling do_wordlist_importer
17:09:11 background-worker.1 | resque-scheduler: [INFO] 2017-05-25T17:09:11+10:00: Scheduling do_cleanUp
17:09:11 background-worker.1 | resque-scheduler: [INFO] 2017-05-25T17:09:11+10:00: Schedules Loaded
17:09:11 background-worker.1 | Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/rvm/gems/ruby-2.2.2/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
17:09:11 background-worker.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /usr/local/rvm/gems/ruby-2.2.2/gems/resque-1.27.4/lib/resque/data_store.rb:59:in `method_missing')
17:09:11 web.1               | exited with code 1
17:09:11 system              | sending SIGTERM to all processes
17:09:11 redis.1             | 17591:signal-handler (1495696151) Received SIGTERM scheduling shutdown...
17:09:11 redis.1             | 17591:M 25 May 17:09:11.771 # User requested shutdown...
17:09:11 redis.1             | 17591:M 25 May 17:09:11.771 * Saving the final RDB snapshot before exiting.
17:09:11 redis.1             | 17591:M 25 May 17:09:11.775 * DB saved on disk
17:09:11 redis.1             | 17591:M 25 May 17:09:11.775 # Redis is now ready to exit, bye bye...
17:09:11 redis.1             | exited with code 0
17:09:11 mgmt-worker.1       | terminated by SIGTERM
17:09:12 hashcat-worker.1    | terminated by SIGTERM
17:09:12 background-worker.1 | terminated by SIGTERM

# netstat -an | egrep ^tcp | grep LIST
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN
tcp6       0      0 :::110                  :::*                    LISTEN
tcp6       0      0 :::143                  :::*                    LISTEN
tcp6       0      0 :::80                   :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::25                   :::*                    LISTEN

Attempting to run hashview.rb manually yields the following:
# RACK_ENV=production ruby /opt/hashview/hashview.rb &
[1] 2726
APPLICATION VERSION: 0.6.1
DB:VERSION 0.6.1
/usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:40:in `check_anchors': regular expression should not contain ^: "^(?!\\/(login|register|logout|v1\\/))" (Mustermann::CompileError)
	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:31:in `compile'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regexp_based.rb:19:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/regular.rb:25:in `initialize'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `new'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `block in new'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/equality_map.rb:39:in `fetch'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann/pattern.rb:59:in `new'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/mustermann-1.0.0/lib/mustermann.rb:67:in `new'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1638:in `compile'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1626:in `compile!'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1357:in `add_filter'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1345:in `before'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/sinatra-2.0.0/lib/sinatra/base.rb:1923:in `block (2 levels) in delegate'
	from /opt/hashview/hashview.rb:30:in `<main>'

[1]+  Exit 1                  RACK_ENV=production ruby /opt/hashview/hashview.rb

**Comment by iontodd** [comment]
Give this a read through and see if it helps:
https://github.com/hashview/hashview/issues/290

**Comment by ama21n** [comment]
Great! That worked with the Gemfile.lock saved over and running bundle install again.FWIW, (only if u needed any further troubleshooting from me)  I tried first to just adjust just the sinatra version in the Gemlock but got the following error:Internal Server Errorundefined method `bytesize' for Rack::Utils:ModuleWEBrick/1.3.1 (Ruby/2.2.2/2015-04-13) OpenSSL/1.0.2g at 10.11.1.200:4567
Using your gemlock the packages it fetched were:Fetching minitest 5.10.1Fetching rack 1.6.5
Fetching erubis 2.7.0Fetching sass 3.4.23
Fetching haml 4.0.7
Fetching nokogiri 1.7.1
Fetching rubocop 0.48.1Fetching activesupport 4.2.8Fetching et-orbi 1.0.3Fetching mail 2.6.4
Fetching rails-deprecated_sanitizer 1.0.3
Fetching rufus-scheduler 3.4.0
Fetching rails-dom-testing 1.0.8
Fetching actionview 4.2.8
Fetching actionpack 4.2.8
Fetching railties 4.2.8
Fetching coffee-rails 4.2.1
Fetching twitter-bootstrap-rails 3.2.2
Fetching resque-web 0.0.10

cheers - Rob 

    On Thursday, 25 May 2017, 18:15, Ion Todd <notifications@github.com> wrote:
 

 Give this a read through and see if it helps:
#290—

**Comment by ccammilleri** [comment]
hotfix has been added for this issue (and #290). ref b8b7ab7ab286ba901f5a6cea8ca28919c9babf6b
