### ISSUE TITLE
Hashcat local worker failes to contact the interface

### ISSUE THREAD

**Issue by hegusung** [hashview/hashview#305]
Hi, 

I manage to install hashview properly on an ubuntu server but it still fails on my mint (issue #208) (pulled the sources yesterday)

I took time to investigate more, It seems the hashcat worker fails to contact the web API, it blocks right after RestClient performs a post for the heartbeat (doesn't return anything, the web server doesn't seem to get the request). Manual POST request to the API using curl and the same url works (added a print in the code).

In the web Interface under the agent tab the last heartbeat is blank, it seems to confirm my suspicions

I stopped my firewall and didn't solve anything, is anyone aware of some issues with ruby RestClient ?

**Comment by ccammilleri** [comment]
@hegusung I haven't heard of any issues with restclient. Do you have anymore details? Is your hashcat path setup correctly?

**Comment by hegusung** [comment]
Yes, when a run the command line provided by the web interface hashcat works.

I put a print before and after the RestClient call and I clearly saw the first print but not the other.

I will try to completely reinstall ruby on my host to see if it solves something

**Comment by ccammilleri** [comment]
we recently landed 0.7-beta which contains a gemfile.lock that will lock all gems. your issue could be related to gem incompatibility. if this isn't your issue i could see stale resque workers causing a similar behavior...if thats the case just forcefully kill all resque tasks via cmd line and restart hashview.
