### ISSUE TITLE
Your [DB] installation is out of date, please run the following upgrade task.

### ISSUE THREAD

**Issue by dennisstewart** [hashview/hashview#319]
While attempting to start Hashview with `RACK_ENV=production TZ='America/New_York' foreman start` on Ubuntu 14.04, I get the following error:

`12:15:42 web.1               | /home/hash/hashview/helpers/hashimporter.rb:360: warning: character class has '-' without escape`
`12:15:42 web.1               | APPLICATION VERSION: 0.7.0`
`12:15:42 web.1               | DB:VERSION`
`12:15:42 web.1               |`
`12:15:42 web.1               |`
`12:15:42 web.1               | Your installation is out of date, please run the following upgrade task.`
`12:15:42 web.1               | RACK_ENV=production rake db:upgrade`

When I run `RACK_ENV=production rake db:upgrade`, I get the following:

`[*] Connecting to DB`
`[*] Collecting table information on Settings`
`[*] Your version is up to date!`

Attempting to start Hashview again gives me the same error. Is the DB version not being detected properly?

**Comment by ccammilleri** [comment]
odd...i'm guessing you ran `RACK_ENV=production rake db:setup` successfully? I'd be curious to see what your database has under the settings table.

I'm assuming your doing a fresh install and not an upgrade?

**Comment by dennisstewart** [comment]
I had a previous borked install, was replacing it.  When I ran `RACK_ENV=production rake db:setup` I got
```setting up database for environment: production
+------------------------------+
| @@global.innodb_large_prefix |
+------------------------------+
|                            1 |
+------------------------------+
+-----------------------------+
| @@global.innodb_file_format |
+-----------------------------+
| Barracuda                   |
+-----------------------------+
ERROR 1007 (HY000) at line 1: Can't create database 'hashview'; database exists
Creating Hashes Table
[*] Building the rest of the tables from datamapper
[*] Setting up default settings ...
[*] Setting default theme ...
[*] Setting up default customer ...
[*] Setting up default Smart Wordlist ...
[*] Settings up default wordlist ...
[*] Setting up default dictionary
[*] Setting up default dictionary + rule task
[*] Setting up default smart wordlist task
[*] Setting up Smart Wordlist dictionary + rule task
[*] Setting up default mask task
[*] Setting up default brute task
[*] Setting up default hub settings
setting up local agent for environment: production
[*] Setting up local agent
provision_agent executed
```

DB credentials haven't changed, and I want to keep the content I already had in my DB.

**Comment by ccammilleri** [comment]
what does a `select * from settings` look like in your hashview db?

**Comment by dennisstewart** [comment]
I got 
```mysql> select * from settings;
+----+------------------------+--------------+-------------+------------+-------------+-----------+-----------+--------------+----------------+------------+-------------+-----------+---------+------------+
| id | hcbinpath              | hcglobalopts | maxtasktime | maxjobtime | smtp_server | smtp_user | smtp_pass | smtp_use_tls | smtp_auth_type | clientmode | smtp_sender | ui_themes | version | chunk_size |
+----+------------------------+--------------+-------------+------------+-------------+-----------+-----------+--------------+----------------+------------+-------------+-----------+---------+------------+
|  1 | /usr/local/bin/hashcat | NULL         | 86400       | NULL       | 10.1.60.30  | NULL      | NULL      |            0 | None           |       NULL | NULL        | Light     | NULL    |     500000 |
|  2 | NULL                   | NULL         | NULL        | NULL       | NULL        | NULL      | NULL      |         NULL | NULL           |       NULL | NULL        | Light     | 0.7.0   |     500000 |
+----+------------------------+--------------+-------------+------------+-------------+-----------+-----------+--------------+----------------+------------+-------------+-----------+---------+------------+
2 rows in set (0.00 sec)
```

I edited the version of id 1 to be 0.7.0 and the application was able to start. Thank you for your support!
