### ISSUE TITLE
Internal Server Error when starting job

### ISSUE THREAD

**Issue by rurapenthe** [hashview/hashview#320]
I cant seem to run new tasks on my server. I can configure it and set it up but if i try to run it I get an internal server error. The output from log is:

2017-08-01 00:08:37 - NoMethodError - undefined method `hash_str' for nil:NilClass:
00:08:37 web.1               | 	/hashview/routes/customers.rb:209:in `block in <top (required)>'
00:08:37 web.1               | 	/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
00:08:37 web.1               | 	/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
... repeated many times

I should note that I have Hashview on its own dedicated server, not the GPU machines (they have remote agents) - therefore i have not configured the agent on the local Hashview machine. I'm not sure if that could be a problem?

Also, my wordlists get uploaded but they all show as 0 size in Hashview, but on the folder where it uploads them to they are fine.
Thx.

**Comment by i128** [comment]
1) the customers.rb should not be called during job start. Chances are, if
you are seeing that error, the job is currupt. I'd recommend deleting it
and create a new one.

2) as for the word list sizes. Check after a few minutes. Do there sizes
change at all? There should be a background tasks that counts the number of
entries and updates the db. If it doesn't update, you might have a hung
thread. Reboot and restart the app

**Comment by ccammilleri** [comment]
@rurapenthe as of now hashview requires the master instance to have a working hashcat local agent. This is because it uses hashcat to compute keyspace for the tasks. You will get odd behavior and errors without it, but not sure if that's the cause of your posted error.

**Comment by rurapenthe** [comment]
Thanks guys, re the local agent i did not have one. i've become quite busy and got side-tracked with something else. I'll test it out soon and close this if that was the problem.
