### ISSUE TITLE
Unable to upload Wordlist

### ISSUE THREAD

**Issue by Chridolc** [hashview/hashview#33]
Hello.
when i try to upload a wordlist : 
- add name (ex : frenchpw)
- select password file (txt format, 171 kb file)
-  clicking upload button

=> name field turn red / empty with "This field is required", file name emptied too.

Tested on a debian 11 machine, hashview running with --debug and raised no errors.
symptoms occured wuth a biggest file too (crackstation txt file)

Thanks for your help.

**Comment by i128** [comment]
So there's two issues here. The returned error message claiming you didnt fill out the name when you say that you did.
I am unable to replicate this issue on my end. A few questions:

Are all wordlist uploads failing or was it just the frenchpw one?
Were you attempting to upload other wordlists at the same time (perhaps in other tabs?)

The second issue is with large wordlists, like crackstation.txt. Yeah this is a problem. What I have found is that the browser will attempt to load the entire dictionary into memory first before sending it to the server. And when those word lists are HUGE, browsers tend to choke.  I don't have a good solution for this at the moments.  Previous versions of hashview had a feature that allowed users to scp the large wordlist to a folder and then the server would periodically read the directory and import it that way. Thus bypassing the browser all together. That feature was not carried over with this port, but perhaps that  is a proper fix

Alternatively, hashcat supports gziped wordlists. Right now hashview only supports plaintext, but another solution would be to support both file formats. It'd make the upload process quicker. BUT if the file size of the gzipd wordlist was huge, we'd still run into the same problem.

**Comment by Chridolc** [comment]
Hello.
i've entered a name for the list, of course ! and with a small file (171 kb).  and tested mutliple times.
I have a doubt with the vm used for testing, because everything was on the same machine (server / client / browser). So, i've created a new one, debian server (no ui), then accessing hashview from another machine => upload is workink with this smaller file.

Of course, making hashview working with Crackstation / weakpass would  be great :-).  i'm actualy looking for a software like hashview to include it in a production environment before the end of the year.
