### ISSUE TITLE
Error loading the GUI library

### ISSUE THREAD

**Issue by afarney** [hashview/hashview#333]
I am trying to fix a broken install by installing all over again. I got to the point where I am able to fire up and connect to Hashview, and log in. However it does not tell me that my cards are functioning on the front page like it used to. I looked over at the handler and I get two errors:

14:33:48 web.1               |        ERROR: libgtk-3.so.0: cannot open shared object file: No such file or
14:33:48 web.1               |        directory
14:33:48 web.1               |        libnvidia-gtk3.so: cannot open shared object file: No such file or
14:33:48 web.1               |        directory
14:33:48 web.1               |        libgtk-x11-2.0.so.0: cannot open shared object file: No such file or
14:33:48 web.1               |        directory
14:33:48 web.1               |        libnvidia-gtk2.so: cannot open shared object file: No such file or
14:33:48 web.1               |        directory

14:34:49 web.1               |       ERROR: A problem occured when loading the GUI library. Please check your
14:34:49 web.1               |        installation and library path. You may need to specify this library
14:34:49 web.1               |        when calling nvidia-settings. Please run `nvidia-settings --help`
14:34:49 web.1               |        for usage information.

I am not sure what the problem is as I am able to run hashcat benchmarks with all 6 cards functioning.

**Comment by i128** [comment]
Are you using the nvidia drivers or ocldrivers?

**Comment by afarney** [comment]
```
nvidia-settings:  version 375.26  (buildmeister@swio-display-x86-rhel47-01)  Thu Dec  8 19:06:44 PST 2016
  The NVIDIA X Server Settings tool.

  This program is used to configure the NVIDIA Linux graphics driver.
  For more detail, please see the nvidia-settings(1) man page.
```
This was the output from nvidia-settings -v

**Comment by afarney** [comment]
Oh I see, when i run

```
nvidia-settings
```
I get the same errors as above

**Comment by i128** [comment]
re-reading. we've removed the portion on the front page where it displayed the card status (became too difficult to support/parse amd/nvidia/ocl outputs). I believe that error message can be ignored (we get it too and still are able to run the app w/o issue). Its probably generated from old code that needs to be stripped

**Comment by afarney** [comment]
Excellent, that's what I needed to know. Thank you very much!
