### ISSUE TITLE
Wordlist not appearing to import

### ISSUE THREAD

**Issue by afarney** [hashview/hashview#334]
I have a small wordlist of confirmed passwords ~350, I tried to import the file into Hashview, via browsing to the file and naming it. I get the mgmt log that says it generates a checksum for it but no visible way of determining whether or not it is actually importing. The wordlist shows 0 words in the file according to the entry in the Wordlists page. The import for the hashfile was great, it told me how many hashes there were and it was pretty fast. 

I tried the method for dropping it in the hashview/control/wordlists folder, but I have not seen anything happen yet and there is no entry into the Wordlists page.

**Comment by i128** [comment]
What's the name / file extension of the wordlists?

**Comment by i128** [comment]
Scratch that...if you tried importing via gui then file extension won't
matter.  Chances are the dedicated background Jon designed to run the
important is failing or crashed.  To fix either restart hashview or the
server and import again.  Let me know if that doesn't work

**Comment by afarney** [comment]
Yup, restarting the server seemed to work great. I had three of the same file imported. I think we are good, thanks man.
