### ISSUE TITLE
Internal Server Error when sending Emails

### ISSUE THREAD

**Issue by GrepItAll** [hashview/hashview#341]
When I attempt to send a test email from global settings, I get this error in the console:

``14:06:24 web.1               | 2017-10-02 14:06:23 - NameError - undefined local variable or method `smtp_sender' for #<Sinatra::Application:0x007f2b3d7ffd90>:
14:06:24 web.1               | 	/home/user/Desktop/hashview/helpers/email.rb:13:in `sendEmail'
14:06:24 web.1               | 	/home/user/Desktop/hashview/routes/settings.rb:209:in `block in <top (required)>'
``
I've just taken the first few lines as this appears to show the root of the problem.

I hope that helps somewhat, if there's any more info that you need from me then please ask.

**Comment by i128** [comment]
Do you have your SMTP settings configured in the Global Setting section of the web app?

**Comment by GrepItAll** [comment]
Yes I do, configured to match this document: https://help.1and1.co.uk/mail-c65093/1and1-mail-basic-c40987/getting-started-c43521/set-up-e-mail-clients-using-imap-or-pop3-a619070.html

The same settings work with my normal email client. Deliberately putting in wrong settings provides the same error about an undefined variable.

**Comment by i128** [comment]
Can you connect to your mysqldb
`mysql -u root -p <your pass>`

Connect to the hashview db
```
use hashview; 
```

Check to see if the entries you typed in match whats listed in the table:
`select * from settngs;`


Note the password is saved in clear text, so dont post it here, but validate that those settings look correct. It should look something like this:
![image](https://user-images.githubusercontent.com/2417131/31154556-8ed66e00-a86d-11e7-813a-dde766538be2.png)

**Comment by GrepItAll** [comment]
Yep, the settings in the first row look correct to me (provided ClientMode is meant to be NULL). However I also have a second row (ID=2), where all the smtp stuff is set to NULL. Is this meant to happen? Should I try deleting the row and restarting hashview?

**Comment by i128** [comment]
Hm. Okay i'll have to look into this further, not sure whats causing it, but will try to replicate locally.

**Comment by GrepItAll** [comment]
Ok, thank you. I just checked it with a different SMTP server (different email), same thing.

**Comment by i128** [comment]
So i think i've isolated the issue and implemented a fix, should be available in v0.7.2-beta

**Comment by i128** [comment]
Closing, let me know if this comes back up.
