### ISSUE TITLE
Incorrect number of Dictionary Rules displayed in Tasks List

### ISSUE THREAD

**Issue by GrepItAll** [hashview/hashview#342]
If I click on the info icon next to the task 'English Dictionary + hob064 rules', Dictionary Rules is displayed as 7. 

This is not correct, as there are 64 rules in this file. 

If I click the info button next to a task using a ruleset I created with 75 rules, Dictionary Rules displays 30.

**Comment by i128** [comment]
Can you provide a screenshot including the size for from the rules page (with the specific rules you're referring to). Can you also provide a second screen shot of the info page showing the wrong count?

For the hob064.rule, is this your own rule set, or one that came with hashview? Did you modify it at all?
Did you create a task first, then modify the rule after it was created?

**Comment by GrepItAll** [comment]
This first screenshot shows the correct number of lines in hob064.rule:

![correct_rule_count](https://user-images.githubusercontent.com/32456461/31115353-e5997984-a819-11e7-8e6e-2e046790ddab.PNG)

This screenshot shows the erroneous count being displayed:
![incorrect_rule_count](https://user-images.githubusercontent.com/32456461/31115359-e988ed18-a819-11e7-9762-dc46268df7f6.PNG)

This is the ruleset that came with Hashview and has not been changed at all. I have tried creating new tasks using this ruleset and the same thing happens

**Comment by i128** [comment]
KK, isolated the issue. the number you're seeing isnt the number of rules, but rather the rule_id (the index number used for the rules table in the db). In fact, that row was never meant to show the rule count, but rather just the name of the rule assigned to the task. That said, i've updated the code in the dev branch to correctly show the name and rule count.
![image](https://user-images.githubusercontent.com/2417131/31154341-194edf7e-a86c-11e7-90e8-772f55aa15aa.png)

**Comment by GrepItAll** [comment]
That's perfect, thanks for resolving that so quickly!

**Comment by i128** [comment]
Closing, let me know if this comes back up.
