### ISSUE TITLE
AWS RDS Connectivity Failure

### ISSUE THREAD

**Issue by xenoptrix** [hashview/hashview#351]
By a random stroke of luck, I spoke with you guys outside at Derbycon a couple of weeks ago regarding this issue, and figured I'd fill you in on the details of the issues I was experiencing. I've attached my build script, which is intended for use on a standard CentOS 7 AWS AMI with a fresh build. Ultimately, the Hashview installation will get to the point where it is attempting to connect to the database, successfully do so, and then fail. Debugging shows that for some reason, it's still attempting to access localhost instead of the hostname provided in the database credentials yml file.

I had intended on using Hashview as part of a GPU based cracking solution I was proposing for a client, but they insisted on utilizing a cloud based / separately managed database solution (AWS RDS). Technically, this should be possible provided the correct database credentials.

I'm convinced the problem lies in the Rakefile, but I could be mistaken.

[install_script.txt](https://github.com/hashview/hashview/files/1377515/install_script.txt)

@sethludwig

**Comment by i128** [comment]
Hey thanks for reporting this! I think you're onto the right issue. 
http://www.rubydoc.info/github/datamapper/dm-core/DataMapper
Shows that the variable in the config should be called host: not hostname:
It must default to localhost if unset, (and annoyingly not report when you submit an unexpected value). We've always run the db locally, so we've never ran into this, but i think you're right. I'll test it out and report back.

**Comment by xenoptrix** [comment]
Makes sense! Please let me know what you find. I can try my own individual testing otherwise. I'd much rather use Hashview than the current solution, for reasons we discussed at the conference. Thanks for looking into it, and as always...keep up the great work!

**Comment by i128** [comment]
Verified this is the case, fix implemented in dev branch v0.7.2-dev

**Comment by xenoptrix** [comment]
Awesome! Thanks a ton bro. I'll let the customer know. I'll be following this project, and let you know if I find anything else worth contributing! :)

**Comment by i128** [comment]
Sounds good. Just one quick note if they have it installed already, the 'upgrade' wont overwrite/update their existing database_config.yml. They'll need to do it manually (right now anyways... I should probably make a rake task for it during the upgrade process)

**Comment by xenoptrix** [comment]
You're the best. Much appreciated, and again...thank you for the work you guys do.

**Comment by i128** [comment]
Closing, let me know if this comes back up.
