### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by wfsunwj** [hashview/hashview#356]
I hope this isn't seen as a duplicate of #349

I have created a job containing 1 task. Upon trying to start the job, I get 'Internal Server Error', but upon going back to the job queue, I can see that the job says 'queued' (hourglass icon), but nothing is currently running.

This is a few lines of the error chucked into the console:
10:37:01 web.1               | 2017-11-03 10:37:01 - NoMethodError - undefined method `hash_id' for nil:NilClass:
10:37:01 web.1               |  /home/hash/hashview/helpers/build_crack_cmd.rb:20:in `buildCrackCmd'
10:37:01 web.1               |  /home/hash/hashview/routes/jobs.rb:392:in `block (2 levels) in <top (required)>'
10:37:01 web.1               |  /home/hash/hashview/routes/jobs.rb:378:in `each'
10:37:01 web.1               |  /home/hash/hashview/routes/jobs.rb:378:in `block in <top (required)>'

**Comment by GrepItAll** [comment]
Not sure about those particular errors, but I have seen the hourglass icon on jobs with nothing running if the hashcat-worker has failed to start successfully.

**Comment by wfsunwj** [comment]
The problem has been found: it may be that the reinstallation of Hashview causes the UUID in config/agent_config.json to be not updated

**Comment by wfsunwj** [comment]
The problem has been found: it may be that the reinstallation of Hashview causes the UUID in config/agent_config.json to be not updated.

**Comment by jahawkins** [comment]
I am having the same issue as @wfsunwj. Are you able to provide the steps you took to resolve the issue?

**Comment by wfsunwj** [comment]
@jahawkins 
The UUID in the configuration file config/agent_config.json is consistent with the UUID in the database agents

**Comment by useyangliu** [comment]
i have same question,but uuid is the same with the UUID in the database agents
anyone have the same question?

**Comment by useyangliu** [comment]
add   i am in vm  kali linux

**Comment by wfsunwj** [comment]
@useyangliu IMPORTANT: Confirm hashcat is working via command line

**Comment by useyangliu** [comment]
hashcat can run,If I run alone 。 and Are there any other possibilities

**Comment by i128** [comment]
is the hashview app running with the proper permissions to execute hashcat?

**Comment by useyangliu** [comment]
`user@kali:/root/hashcat-4.0.1$ ./hashcat64.bin -m 1000 -b
hashcat (v4.0.1) starting in benchmark mode...

Benchmarking uses hand-optimized kernel code by default.
You can use it in your cracking session by setting the -O option.
Note: Using optimized kernel code limits the maximum supported password length.
To disable the optimized kernel code in benchmark mode, use the -w option.

* Device #1: Not a native Intel OpenCL runtime. Expect massive speed loss.
             You can use --force to override, but do not report related errors.
OpenCL Platform #1: The pocl project
====================================
* Device #1: pthread-Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz, skipped.

OpenCL Platform #2: Intel(R) Corporation
========================================
* Device #2: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz, 499/1999 MB allocatable, 4MCU

Benchmark relevant options:
===========================
* --optimized-kernel-enable

Hashmode: 1000 - NTLM

Speed.Dev.#2.....:   332.8 MH/s (7.85ms)

Started: Tue Dec 26 19:56:33 2017
Stopped: Tue Dec 26 19:56:38 2017
`

i can run in user 
`+--------------------------------------+
| uuid                                 |
+--------------------------------------+
| d8f13289-207b-4d3d-a695-4fc6e5a4f703 |
+--------------------------------------+
`
`{
  "ip": "127.0.0.1",
  "port": "4567",
  "uuid": "d8f13289-207b-4d3d-a695-4fc6e5a4f703",
  "hc_binary_path": "/root/hashcat-4.0.1/hashcat64.bin",
  "type": "master"
}
`
UUID is same @i128 @wfsunwj 

I'm going crazy. Is there anything else
I've reinstalled it, but it's no use

**Comment by i128** [comment]
Can you either 
1) reboot the server or 
2) stop hashview, and run a ps -ef | grep resque to see if there are any stale threads?

To confirm, you're running hashview (or foreman) as root?

**Comment by useyangliu** [comment]
i reboot the server 
when i do nothing  ps -ef | grep resque is ok 

 i  run a ps -ef | grep resque when the job says 'queued' (hourglass icon) 
user      3165  3162  0 22:07 pts/1    00:00:00 sh -c TERM_CHILD=1 COUNT=5 QUEUE=management rake resque:workers
user      3166  3162  0 22:07 pts/1    00:00:00 sh -c TERM_CHILD=1 COUNT=1 QUEUE=hashcat rake resque:work
user      3167  3165  9 22:07 pts/1    00:00:01 ruby /home/user/.rvm/gems/ruby-2.2.2/bin/rake resque:workers
user      3168  3162  0 22:07 pts/1    00:00:00 sh -c QUEUE=* rake resque:scheduler
user      3169  3166  8 22:07 pts/1    00:00:01 resque-1.26.0: Forked 3223 at 1514344042
user      3171  3168  9 22:07 pts/1    00:00:01 resque-scheduler-4.3.0: Schedules Loaded
user      3186  3167  8 22:07 pts/1    00:00:00 resque-1.26.0: Waiting for management
user      3187  3167  7 22:07 pts/1    00:00:00 resque-1.26.0: Waiting for management
user      3190  3167  7 22:07 pts/1    00:00:00 resque-1.26.0: Waiting for management
user      3191  3167  9 22:07 pts/1    00:00:00 resque-1.26.0: Waiting for management
user      3193  3167  7 22:07 pts/1    00:00:00 resque-1.26.0: Waiting for management
user      3223  3169  0 22:07 pts/1    00:00:00 resque-1.26.0: Processing hashcat since 1514344042 [LocalAgent]
root      3234  1553  0 22:07 pts/0    00:00:00 grep resque

when not 'queued' 
user      3165  3162  0 22:07 pts/1    00:00:00 sh -c TERM_CHILD=1 COUNT=5 QUEUE=management rake resque:workers
user      3166  3162  0 22:07 pts/1    00:00:00 sh -c TERM_CHILD=1 COUNT=1 QUEUE=hashcat rake resque:work
user      3167  3165  0 22:07 pts/1    00:00:01 ruby /home/user/.rvm/gems/ruby-2.2.2/bin/rake resque:workers
user      3168  3162  0 22:07 pts/1    00:00:00 sh -c QUEUE=* rake resque:scheduler
user      3169  3166  0 22:07 pts/1    00:00:01 resque-1.26.0: Forked 3223 at 1514344042
user      3171  3168  0 22:07 pts/1    00:00:01 resque-scheduler-4.3.0: Schedules Loaded
user      3186  3167  0 22:07 pts/1    00:00:00 resque-1.26.0: Waiting for management
user      3187  3167  0 22:07 pts/1    00:00:00 resque-1.26.0: Forked 3637 at 1514344208
user      3190  3167  0 22:07 pts/1    00:00:00 resque-1.26.0: Waiting for management
user      3191  3167  0 22:07 pts/1    00:00:01 resque-1.26.0: Waiting for management
user      3193  3167  0 22:07 pts/1    00:00:00 resque-1.26.0: Waiting for management
user      3223  3169  0 22:07 pts/1    00:00:00 resque-1.26.0: Processing hashcat since 1514344042 [LocalAgent]
user      3637  3187  0 22:10 pts/1    00:00:00 resque-1.26.0: Processing management since 1514344208 [RuleImporter]
root      3669  1553  0 22:10 pts/0    00:00:00 grep resque
@i128  aaaaaaaaaa.......... help me

**Comment by i128** [comment]
Can you provide the output of:
logs/jobs/background_worker.log?

Also, in another terminal, after hashview is running but before a job is queued to start, run the following command
`redis-cli monitor > /tmp/output.txt`
once thats running, go ahead and queue a job. It should capture any redis error messages. reply back with the output of /tmp/output.txt

**Comment by useyangliu** [comment]
/tmp/output.log 
`OK
1514356323.554946 [0 127.0.0.1:47282] "lpop" "resque:queue:management"
1514356324.171645 [0 127.0.0.1:47272] "evalsha" "8f4a4e422bfa8f9a0931e350d6e30b1c3ce97c33" "1" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.171671 [0 lua] "SETNX" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.171848 [0 127.0.0.1:47272] "evalsha" "8d4e4994f7049799013e71b43d439219209e9f57" "1" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.171860 [0 lua] "GET" "resque:resque:resque_scheduler_master_lock"
1514356324.171868 [0 lua] "EXPIRE" "resque:resque:resque_scheduler_master_lock" "180"
1514356324.171884 [0 lua] "GET" "resque:resque:resque_scheduler_master_lock"
1514356324.172318 [0 127.0.0.1:47272] "evalsha" "8f4a4e422bfa8f9a0931e350d6e30b1c3ce97c33" "1" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.172346 [0 lua] "SETNX" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.172591 [0 127.0.0.1:47272] "evalsha" "8d4e4994f7049799013e71b43d439219209e9f57" "1" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.172603 [0 lua] "GET" "resque:resque:resque_scheduler_master_lock"
1514356324.172610 [0 lua] "EXPIRE" "resque:resque:resque_scheduler_master_lock" "180"
1514356324.172615 [0 lua] "GET" "resque:resque:resque_scheduler_master_lock"
1514356324.172863 [0 127.0.0.1:47272] "hset" "resque:delayed:last_enqueued_at" "do_wordlist_importer" "2017-12-27 14:32:04 +0800"
1514356324.173209 [0 127.0.0.1:47272] "hset" "resque:delayed:last_enqueued_at" "do_rulelist_importer" "2017-12-27 14:32:04 +0800"
1514356324.173482 [0 127.0.0.1:47272] "sadd" "resque:queues" "management"
1514356324.173520 [0 127.0.0.1:47272] "rpush" "resque:queue:management" "{\"class\":\"WordlistImporter\",\"args\":[]}"
1514356324.173715 [0 127.0.0.1:47272] "sadd" "resque:queues" "management"
1514356324.173753 [0 127.0.0.1:47272] "rpush" "resque:queue:management" "{\"class\":\"RuleImporter\",\"args\":[]}"
1514356324.527870 [0 127.0.0.1:47272] "evalsha" "8f4a4e422bfa8f9a0931e350d6e30b1c3ce97c33" "1" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.527892 [0 lua] "SETNX" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.527997 [0 127.0.0.1:47272] "evalsha" "8d4e4994f7049799013e71b43d439219209e9f57" "1" "resque:resque:resque_scheduler_master_lock" "kali:2036"
1514356324.528008 [0 lua] "GET" "resque:resque:resque_scheduler_master_lock"
1514356324.528018 [0 lua] "EXPIRE" "resque:resque:resque_scheduler_master_lock" "180"
1514356324.528036 [0 lua] "GET" "resque:resque:resque_scheduler_master_lock"
1514356324.528133 [0 127.0.0.1:47272] "zrangebyscore" "resque:delayed_queue_schedule" "-inf" "1514356324" "LIMIT" "0" "1"
1514356325.758068 [0 127.0.0.1:47284] "lpop" "resque:queue:management"
1514356325.758391 [0 127.0.0.1:47284] "set" "resque:worker:kali:2057:management" "{\"queue\":\"management\",\"run_at\":\"2017-12-27T06:32:05Z\",\"payload\":{\"class\":\"WordlistImporter\",\"args\":[]}}"
1514356326.021748 [0 127.0.0.1:47278] "lpop" "resque:queue:management"
1514356326.022037 [0 127.0.0.1:47278] "set" "resque:worker:kali:2056:management" "{\"queue\":\"management\",\"run_at\":\"2017-12-27T06:32:06Z\",\"payload\":{\"class\":\"RuleImporter\",\"args\":[]}}"
1514356326.470950 [0 127.0.0.1:47280] "lpop" "resque:queue:management"
1514356327.505947 [0 127.0.0.1:47274] "lpop" "resque:queue:management"`
 background_worker.log 
`
I, [2017-12-26T19:04:49.079361 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:04:53.163041 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:04:57.231954 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:05:01.298982 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:05:05.363584 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:05:09.427686 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:05:17.088261 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:05:21.159599 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:05:25.240106 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:05:29.307700 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}
I, [2017-12-26T19:05:33.427068 #16759]  INFO -- : {"status"=>200, "type"=>"message", "msg"=>"OK"}`

   
@i128

**Comment by i128** [comment]
Hm, that all looks right (presuming the dates/times are accurate). 
Lets check the DB
```
mysql -u root -p <your db password>
use hashview;
select * from jobs;
select * from jobtasks;
select * from taskqueues;
```

**Comment by useyangliu** [comment]
MariaDB [hashview]> select * from jobs;
+----+------+-----------------+---------------------+--------+---------------------+------------+---------------------+-------------+-------------+------------------+
| id | name | last_updated_by | updated_at          | status | queued_at           | started_at | ended_at            | hashfile_id | customer_id | notify_completed |
+----+------+-----------------+---------------------+--------+---------------------+------------+---------------------+-------------+-------------+------------------+
|  1 | 1    | root            | 2017-12-25 10:59:43 | NULL   | NULL                | NULL       | NULL                |        NULL |           1 |                0 |
|  2 | 2222 | root            | 2017-12-27 14:32:04 | Queued | 2017-12-27 14:32:04 | NULL       | 2017-12-27 14:31:54 |           1 |           1 |                0 |
+----+------+-----------------+---------------------+--------+---------------------+------------+---------------------+-------------+-------------+------------------+
2 rows in set (0.00 sec)

MariaDB [hashview]> select * from jobtasks;
+----+--------+---------+-----------+--------+----------+
| id | job_id | task_id | build_cmd | status | run_time |
+----+--------+---------+-----------+--------+----------+
|  1 |      2 |      30 | NULL      | Queued |     NULL |
+----+--------+---------+-----------+--------+----------+
1 row in set (0.00 sec)

MariaDB [hashview]> select * from taskqueues;
Empty set (0.00 sec)

**Comment by i128** [comment]
Ah, we're getting closer....

can you show me the output of 
`select * from tasks;`

**Comment by useyangliu** [comment]
MariaDB [hashview]> select * from tasks;
+----+------------------------------------------+--------+------+---------+-------+---------------+---------+----------------+----------+
| id | name                                     | source | mask | command | wl_id | hc_attackmode | hc_rule | hc_mask        | keyspace |
+----+------------------------------------------+--------+------+---------+-------+---------------+---------+----------------+----------+
|  1 | Basic Dictionary                         | NULL   | NULL | NULL    | 2     | dictionary    | none    | NULL           |     NULL |
|  2 | Basic Dictionary + hob064 Rules          | NULL   | NULL | NULL    | 2     | dictionary    | 5       | NULL           |     NULL |
|  3 | Smart Wordlist Dictionary                | NULL   | NULL | NULL    | 1     | dictionary    | NULL    | NULL           |     NULL |
|  4 | Smart Wordlist Dictionary + hob064 Rules | NULL   | NULL | NULL    | 1     | dictionary    | 5       | NULL           |     NULL |
|  5 | Lower Alpha 7char                        | NULL   | NULL | NULL    | NULL  | maskmode      | NULL    | ?l?l?l?l?l?l?l |     NULL |
|  6 | Raw Brute                                | NULL   | NULL | NULL    | NULL  | bruteforce    | NULL    | NULL           |     NULL |
|  7 | Basic Dictionary                         | NULL   | NULL | NULL    | 2     | dictionary    | none    | NULL           |     NULL |
|  8 | Basic Dictionary + hob064 Rules          | NULL   | NULL | NULL    | 2     | dictionary    | 5       | NULL           |     NULL |
|  9 | Smart Wordlist Dictionary                | NULL   | NULL | NULL    | 1     | dictionary    | NULL    | NULL           |     NULL |
| 10 | Smart Wordlist Dictionary + hob064 Rules | NULL   | NULL | NULL    | 1     | dictionary    | 5       | NULL           |     NULL |
| 11 | Lower Alpha 7char                        | NULL   | NULL | NULL    | NULL  | maskmode      | NULL    | ?l?l?l?l?l?l?l |     NULL |
| 12 | Raw Brute                                | NULL   | NULL | NULL    | NULL  | bruteforce    | NULL    | NULL           |     NULL |
| 13 | Basic Dictionary                         | NULL   | NULL | NULL    | 2     | dictionary    | none    | NULL           |     NULL |
| 14 | Basic Dictionary + hob064 Rules          | NULL   | NULL | NULL    | 2     | dictionary    | 5       | NULL           |     NULL |
| 15 | Smart Wordlist Dictionary                | NULL   | NULL | NULL    | 1     | dictionary    | NULL    | NULL           |     NULL |
| 16 | Smart Wordlist Dictionary + hob064 Rules | NULL   | NULL | NULL    | 1     | dictionary    | 5       | NULL           |     NULL |
| 17 | Lower Alpha 7char                        | NULL   | NULL | NULL    | NULL  | maskmode      | NULL    | ?l?l?l?l?l?l?l |     NULL |
| 18 | Raw Brute                                | NULL   | NULL | NULL    | NULL  | bruteforce    | NULL    | NULL           |     NULL |
| 19 | Basic Dictionary                         | NULL   | NULL | NULL    | 2     | dictionary    | none    | NULL           |     NULL |
| 20 | Basic Dictionary + hob064 Rules          | NULL   | NULL | NULL    | 2     | dictionary    | 5       | NULL           |     NULL |
| 21 | Smart Wordlist Dictionary                | NULL   | NULL | NULL    | 1     | dictionary    | NULL    | NULL           |     NULL |
| 22 | Smart Wordlist Dictionary + hob064 Rules | NULL   | NULL | NULL    | 1     | dictionary    | 5       | NULL           |     NULL |
| 23 | Lower Alpha 7char                        | NULL   | NULL | NULL    | NULL  | maskmode      | NULL    | ?l?l?l?l?l?l?l |     NULL |
| 24 | Raw Brute                                | NULL   | NULL | NULL    | NULL  | bruteforce    | NULL    | NULL           |     NULL |
| 25 | Basic Dictionary                         | NULL   | NULL | NULL    | 2     | dictionary    | none    | NULL           |     NULL |
| 26 | Basic Dictionary + hob064 Rules          | NULL   | NULL | NULL    | 2     | dictionary    | 5       | NULL           |     NULL |
| 27 | Smart Wordlist Dictionary                | NULL   | NULL | NULL    | 1     | dictionary    | NULL    | NULL           |     NULL |
| 28 | Smart Wordlist Dictionary + hob064 Rules | NULL   | NULL | NULL    | 1     | dictionary    | 5       | NULL           |     NULL |
| 29 | Lower Alpha 7char                        | NULL   | NULL | NULL    | NULL  | maskmode      | NULL    | ?l?l?l?l?l?l?l |     NULL |
| 30 | Raw Brute                                | NULL   | NULL | NULL    | NULL  | bruteforce    | NULL    | NULL           |     NULL |
+----+------------------------------------------+--------+------+---------+-------+---------------+---------+----------------+----------+

**Comment by i128** [comment]
Does the job run if you change the task from Raw Brute to  say "Basic Dictionary" ?
What if you create a new job with two different tasks? what happens then?

**Comment by useyangliu** [comment]
still "Internal Server Error".
I don't know where the error is.

**Comment by useyangliu** [comment]
@i128  i am in vmware kali linux

**Comment by i128** [comment]
I suspect the issue is within the helper/buildcrackcommand.rb file.  Unfortunately detailed "Internal Server error 500" message are not displayed when running in production. However, we can still get to the root of the problem.  To do this, you'll need to re-create the issue but by running hashview in development mode. (Note any production data will NOT be erased by doing this)

1) Make sure hashview is not running
2) setup the development hashview database:
`RACK_ENV=development rake db:setup`
3) Start Hashview
`RACK_ENV=development foreman start`
4) Create new users/job etc. and see if the problem occurs again.  If it does, you should now see a more verbose error message that can be helpful in isolating the problem.

**Comment by useyangliu** [comment]
application error
NoMethodError at /jobs/start/1
undefined method `hash_id' for nil:NilClass

    file: build_crack_cmd.rb location: buildCrackCmd line: 20 

BACKTRACE

(expand)

JUMP TO: GET POST COOKIES ENV

    /root/hashview/helpers/build_crack_cmd.rb in buildCrackCmd
            hash_id = Hashfilehashes.first(hashfile_id: hashfile_id).hash_id
    /root/hashview/routes/jobs.rb in block (2 levels) in <top (required)>
              cmds = buildCrackCmd(@job.id, task.id)
    /root/hashview/routes/jobs.rb in each
          tasks.each do |task|
    /root/hashview/routes/jobs.rb in block in <top (required)>
          tasks.each do |task|
    /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb in service
              si.service(req, res)
    /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb in run
                  server.service(req, res)
    /home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb in block in start_thread
                  block ? block.call(sock) : run(sock)

GET

No GET data.
POST

No POST data.

return this  
It's always this mistake
I think the source code is okay, but I don't know where the wrong thing is.

**Comment by i128** [comment]
Interesting, the only reason why hash_id would fail is if there's a problem with the hashfile itself. 
in the database check the following:
```
mysql -u root -p <password>
use hashview_dev;
select * from hashfiles;
select * from hashfilehashes where hashfile_id = '1';
```

Depending on the sensitivity feel free NOT do show the contents of the last command. But im curious if the hash_id is populated under the hashfilehashes table for hashfile_id =1;

What kind of hashes are you uploading?

**Comment by useyangliu** [comment]
ariaDB [hashview_dev]> select * from hashfiles;
+----+-------------+------+----------+----------------+
| id | customer_id | name | hash_str | total_run_time |
+----+-------------+------+----------+----------------+
|  1 |           1 | 1    | hfo7o7sk |              0 |
+----+-------------+------+----------+----------------+
1 row in set (0.00 sec)

MariaDB [hashview_dev]> select * from hashfilehashes where hashfile_id = '1';
Empty set (0.00 sec)

MariaDB [hashview_dev]> 

my hashes is MD5：8743b52063cd84097a65d1633f5c74f5

**Comment by i128** [comment]
okay good news there's your problem, the hashfile isn't properly being loaded into the db! 
to confirm this you do a:
`select * from hashes where id = '1';`

When you're uploading the hash, are you selecting a file? or are you copying / pasting the hash into the box?

are there any extra spaces before or after the hash? i.e.: <space>8743b52063cd84097a65d1633f5c74f5<space>
what happens if you try with a different hash, like: 
a936af92b0ae20b1ff6c3347a72e5fbe

**Comment by useyangliu** [comment]
8743b52063cd84097a65d1633f5c74f5
a936af92b0ae20b1ff6c3347a72e5fbe
all tell me  uploaded 0 hashes.
What's the matter?

**Comment by i128** [comment]
How are you uploading the hash? Copy and paste or file import?

**Comment by useyangliu** [comment]
Copy and paste  not hashfile

**Comment by useyangliu** [comment]
Are you still there? I'm sorry, I asked a bit too much @i128

**Comment by i128** [comment]
What filetype are you selecting on the subsequent steps? 
Does hashview properly identify the hash as MD5?
What happens if you upload the file instead of copy/paste?

**Comment by useyangliu** [comment]
hashview properly identify the hash as MD5
if i upload the file ，hashview still properly identify the hash as MD5
but still 0 hashes.

**Comment by i128** [comment]
Understood, but what **filetype** or **file format** are you selecting?

**Comment by useyangliu** [comment]
thanks,I seem to have solved it, I didn't choose File Type, direct confirm
Thank you for your patient answers

**Comment by AMCRalston** [comment]
Here is a screen shot:
![image](https://user-images.githubusercontent.com/16841655/35520974-8ecfea78-04e6-11e8-9665-ad64cf881cc5.png)

**Comment by i128** [comment]
Go to manage -> hashfiles and look for the hashfile you uploaded. What does that look like? Is there a second number x / y? or is it 0/0?

**Comment by AMCRalston** [comment]
0/0

**Comment by AMCRalston** [comment]
Here is a screen shot:
![image](https://user-images.githubusercontent.com/16841655/35523954-0a2d9be6-04ee-11e8-8488-3e33e02dc2a6.png)

**Comment by AMCRalston** [comment]
Here is the hashfiles in mysql:
![image](https://user-images.githubusercontent.com/16841655/35524378-714d89b6-04ef-11e8-9b5d-244668716b69.png)

**Comment by i128** [comment]
what format are the hashes in the hashfile? username:password, pwdump?

**Comment by AMCRalston** [comment]
NetNTLMv2

**Comment by i128** [comment]
Are you selecting this when prompted: 
![image](https://user-images.githubusercontent.com/2417131/35524609-ad80fca4-04e7-11e8-8ba2-8d88db45e79e.png)

**Comment by AMCRalston** [comment]
I did that the beginning.. However, it was having issues so I let it auto detect. which it seemed to do fine

**Comment by AMCRalston** [comment]
Just wouldn't start the job

**Comment by i128** [comment]
Jobs wont start if there's no hashes to be cracked. And there's no hashes to be cracked because they're failing to import (thus the 0/0 in the hashfile page). What error do you get when you select (NetNTLMv2) for hashfile type?

**Comment by AMCRalston** [comment]
![image](https://user-images.githubusercontent.com/16841655/35524733-715fd7d2-04f0-11e8-9271-7123d75b708c.png)
 Here is the issue when I select it from the drop down

**Comment by i128** [comment]
Ah, yup, thats a typo on my part, just fixed, do a git pull and try again.

**Comment by AMCRalston** [comment]
Working like a champ now
Thanks
