### ISSUE TITLE
Error while creating database: rake aborted!

### ISSUE THREAD

**Issue by TheCrow** [hashview/hashview#361]
I have followed completely the tutorial for installing hashview. I use Ubuntu 17.10.
But I am stuck for days, I hope someone can help me out!
When I am trying to create the database, but it will result in a error:

> user@User:~/hashview$ RACK_ENV=production rake db:setup
rake aborted!
LoadError: cannot load such file -- resque/tasks
/home/user/hashview/Rakefile:1:in `<top (required)>'
>(See full trace by running task with --trace)
 
When I use the --trace:

`user@User:~/hashview$ RACK_ENV=production rake db:setup --trace
rake aborted!
LoadError: cannot load such file -- resque/tasks
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/bruteboy/hashview/Rakefile:1:in `<top (required)>'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/share/rvm/rubies/ruby-2.2.2/bin/rake:33:in `<main>'
`

**Comment by ccammilleri** [comment]
@TheCrow i take it you maybe fixed this since you closed it? We haven't tested on 17.10 (we only test on LTS versions of ubuntu). Curious to know if this is running ok for you?
