### ISSUE TITLE
Error when removing wordlist/rules

### ISSUE THREAD

**Issue by JormungandrYggdrasil** [hashview/hashview#365]
Attempt: Remove wordlist
Condition: File does not exist
Result: Gateway Error

Recommended fix: Remove file from database if file does not exist anymore when attempting to remove it.

**Comment by JormungandrYggdrasil** [comment]
Errno::ENOENT - No such file or directory @ rb_sysopen - control/rules/Incisive-leetspeak.rule:
Same thing with rules

**Comment by i128** [comment]
Looking on the server itself? Are the files there? Chances are they've been
removed, but the DB wasn't updated.

**Comment by i128** [comment]
Agreed. No need to fail hard in these scenarios, just update the db
