### ISSUE TITLE
Cannot start Redis server 

### ISSUE THREAD

**Issue by TheCrow** [hashview/hashview#369]
I followed the tutorial and when I try to start the server with command: 
" RACK_ENV=production TZ='Europe/Amsterdam' foreman start" 
I recieve the following error's, I cannot figure out what the problem is... I am stuck for days.
Could someone help me out?

> 10:02:02
 redis.1             | started with pid 2637
10:02:02 mgmt-worker.1       | started with pid 2638
10:02:02 hashcat-worker.1    | started with pid 2639
10:02:02 background-worker.1 | started with pid 2641
10:02:02 web.1               | started with pid 2643
10:02:02 redis.1             | 2637:C 14 Nov 10:02:02.204 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10:02:02 redis.1             | 2637:C 14 Nov 10:02:02.204 # Redis version=4.0.1, bits=64, commit=00000000, modified=0, pid=2637, just started
10:02:02 redis.1             | 2637:C 14 Nov 10:02:02.204 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
10:02:02 redis.1             | 2637:M 14 Nov 10:02:02.205 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
10:02:02 redis.1             | 2637:M 14 Nov 10:02:02.205 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
10:02:02 redis.1             | 2637:M 14 Nov 10:02:02.205 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
10:02:02 redis.1             | 2637:M 14 Nov 10:02:02.205 # Creating Server TCP listening socket *:6379: bind: Address already in use
10:02:02 redis.1             | exited with code 1
10:02:02 system              | sending SIGTERM to all processes
10:02:02 mgmt-worker.1       | terminated by SIGTERM
10:02:02 hashcat-worker.1    | terminated by SIGTERM
10:02:02 background-worker.1 | terminated by SIGTERM
10:02:02
>web.1               | terminated by SIGTERM

**Comment by i128** [comment]
Looks like there's a few issues.  What OS are you trying it on?

If you do a netstat, is there already something listening on 6379?


On Nov 14, 2017 3:09 AM, "TheCrow" <notifications@github.com> wrote:

I followed the tutorial and when I try to start the server with command:
" RACK_ENV=production TZ='Europe/Amsterdam' foreman start"
I recieve the following error's, I cannot figure out what the problem is...
I am stuck for days.
Could someone help me out?

10:02:02 redis.1 | started with pid 2637
10:02:02 mgmt-worker.1 | started with pid 2638
10:02:02 hashcat-worker.1 | started with pid 2639
10:02:02 background-worker.1 | started with pid 2641
10:02:02 web.1 | started with pid 2643
10:02:02 redis.1 | 2637:C 14 Nov 10:02:02.204 # oO0OoO0OoO0Oo Redis is
starting oO0OoO0OoO0Oo
10:02:02 redis.1 | 2637:C 14 Nov 10:02:02.204 # Redis version=4.0.1,
bits=64, commit=00000000, modified=0, pid=2637, just started
10:02:02 redis.1 | 2637:C 14 Nov 10:02:02.204 # Warning: no config file
specified, using the default config. In order to specify a config file use
redis-server /path/to/redis.conf
10:02:02 redis.1 | 2637:M 14 Nov 10:02:02.205 # You requested maxclients of
10000 requiring at least 10032 max file descriptors.
10:02:02 redis.1 | 2637:M 14 Nov 10:02:02.205 # Server can't set maximum
open files to 10032 because of OS error: Operation not permitted.
10:02:02 redis.1 | 2637:M 14 Nov 10:02:02.205 # Current maximum open files
is 4096. maxclients has been reduced to 4064 to compensate for low ulimit.
If you need higher maxclients increase 'ulimit -n'.
10:02:02 redis.1 | 2637:M 14 Nov 10:02:02.205 # Creating Server TCP
listening socket *:6379: bind: Address already in use
10:02:02 redis.1 | exited with code 1
10:02:02 system | sending SIGTERM to all processes
10:02:02 mgmt-worker.1 | terminated by SIGTERM
10:02:02 hashcat-worker.1 | terminated by SIGTERM
10:02:02 background-worker.1 | terminated by SIGTERM
10:02:02 web.1 | terminated by SIGTERM
`

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hashview/hashview/issues/369>, or mute the thread

**Comment by TheCrow** [comment]
I have a clean install Ubuntu 17.10

When I use netstat:

> netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost:6379          localhost:53860         ESTABLISHED
tcp        0      0 localhost:53964         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53212         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53206         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53094         ESTABLISHED
tcp        0      0 localhost:53998         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53124         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53126         ESTABLISHED
tcp        0      0 localhost:53124         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53130         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53998         ESTABLISHED
tcp        0      0 localhost:53962         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53900         ESTABLISHED
tcp        0      0 localhost:53212         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53972         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53882         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53916         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53878         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53214         ESTABLISHED
tcp        0      0 localhost:53864         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53928         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53864         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53854         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53884         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53972         ESTABLISHED
tcp        0      0 localhost:53856         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53924         ESTABLISHED
tcp        0      0 localhost:53858         localhost:6379          ESTABLISHED
tcp        0      0 localhost:54002         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53208         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53930         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53210         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53202         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53208         ESTABLISHED
tcp        0      0 localhost:54006         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53894         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53084         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53968         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53868         ESTABLISHED
tcp        0      0 localhost:53870         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53880         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53892         ESTABLISHED
tcp        0      0 localhost:53920         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:54008         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53920         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53852         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53896         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53084         ESTABLISHED
tcp        0      0 localhost:53206         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53210         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53964         ESTABLISHED
tcp        4      0 Bruteboy:56440          KAB-TDO-AP0:netbios-ssn ESTABLISHED
tcp        0      0 localhost:6379          localhost:53894         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53846         ESTABLISHED
tcp        0      0 localhost:53874         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53120         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53924         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53088         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53908         ESTABLISHED
tcp        0      0 localhost:54000         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53918         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53872         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53928         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53092         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53120         ESTABLISHED
tcp        0      0 localhost:6379          localhost:54002         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53090         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53096         ESTABLISHED
tcp        0      0 localhost:53880         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53126         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53872         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53132         ESTABLISHED
tcp        0      0 localhost:6379          localhost:54000         ESTABLISHED
tcp        0      0 localhost:53892         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53970         ESTABLISHED
tcp        0      0 localhost:53896         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53858         ESTABLISHED
tcp        0      0 localhost:53866         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53884         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53934         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53930         ESTABLISHED
tcp        0      0 localhost:53846         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53914         ESTABLISHED
tcp        0      0 localhost:6379          localhost:54004         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53886         ESTABLISHED
tcp        0      0 localhost:53096         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:54006         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53088         ESTABLISHED
tcp        0      0 localhost:53912         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53886         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53850         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53202         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53898         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53874         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53966         ESTABLISHED
tcp        0      0 localhost:53852         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53890         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53090         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53214         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53094         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53860         localhost:6379          ESTABLISHED
tcp        0      0 localhost:54004         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53866         ESTABLISHED
tcp        0      0 localhost:53918         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53130         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53086         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53870         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53932         ESTABLISHED
tcp        0      0 localhost:53128         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53850         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53968         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53890         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53086         ESTABLISHED
tcp        0      0 localhost:53914         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53900         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53092         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53878         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53916         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53962         ESTABLISHED
tcp        0      0 localhost:53966         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53932         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53856         ESTABLISHED
tcp        0      0 localhost:53970         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53854         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53936         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53934         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53936         ESTABLISHED
tcp        0      0 localhost:6379          localhost:53128         ESTABLISHED
tcp        0      0 localhost:54008         localhost:6379          ESTABLISHED
tcp        0      0 localhost:53898         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53882         ESTABLISHED
tcp        0      0 localhost:53132         localhost:6379          ESTABLISHED
tcp        0      0 localhost:6379          localhost:53912         ESTABLISHED
tcp        0      0 localhost:53868         localhost:6379          ESTABLISHED
> tcp     0      0 localhost:53908         localhost:6379          ESTABLISHED

**Comment by i128** [comment]
This looks familiar. I think the issue is that redis-server is already running. I believe either foreman or rake tries to start it (not taking into consideration that its already active).  I thought we had a wiki entry on this, but i cant find it. 

try doing a:
`sudo /etc/init.d/redis-server stop`

then try running hashview again using the foreman command listed above.

**Comment by TheCrow** [comment]
Alright it looks like it is starting now, but how could I open the webpanel?
When I enter 127.0.0.1:4567 or 127.0.0.1:4567/home in browser it does not work.
I also tryed my internal IP address.

**Comment by i128** [comment]
What does:

`netstat -lntp | grep 4567` 

Show?

**Comment by TheCrow** [comment]
sudo netstat -lntp | grep 4567
tcp        0      0 0.0.0.0:4567            0.0.0.0:*               LISTEN      2203/ruby           

and when I enter in the browser: 127.0.0.1:4567 the server logs:

`09:18:43 web.1               | 	/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/openssl/ssl.rb:290:in `accept'
`09:18:43 web.1               | [2017-11-15 09:18:43] ERROR OpenSSL::SSL::SSLError: SSL_accept ` `returned=1 errno=0 state=SSLv2/v3 read client hello A: http request
`

**Comment by TheCrow** [comment]
Problem solved! I had to use https:// in URL instead of http://  lol :)

**Comment by tksjk20** [comment]
Hellow,I meet the same problem.Can you tell me the solution in detail？

**Comment by tksjk20** [comment]
I meet the same problem with you .Can you tell me the solution in detail?

**Comment by GrepItAll** [comment]
Try:
`sudo /etc/init.d/redis-server stop`
Then:
`RACK_ENV=production TZ='Europe/Amsterdam' foreman start` with your appropriate timezone

Then make sure to navigtate to https://127.0.0.1:4567, not just http:// (if that is the IP and port you want to access it on)

**Comment by tksjk20** [comment]
WoW！Thank you！The problem is so ……

**Comment by GrepItAll** [comment]
No problem

**Comment by isitavi** [comment]
just run 
sudo service redis-server stop

**Comment by jiuweidao** [comment]
I tried this way, but get this result:
sudo: /etc/init.d/redis-server: command not found
