### ISSUE TITLE
Incorrect estimated time displayed when runtime is limited in bruteforce job

### ISSUE THREAD

**Issue by GrepItAll** [hashview/hashview#371]
![image](https://user-images.githubusercontent.com/32456461/33014508-799be6cc-cddf-11e7-9b43-a0fa943e8999.png)

The time estimated in this screenshot is 6 days 23 hours, but this is actually the time that the runtime is limited to. The actual estimated time is not displayed.

I believe this is because you are just splitting on ':' to parse the output of the hashcat thread, which immediately precedes the time limit.

**Comment by i128** [comment]
I'm not able to replicate, what task are you running where you see this? (presuming raw). Is this from the local agent or a remote?

**Comment by GrepItAll** [comment]
Correct, raw brute. In my global settings, I had a runtime limit of 604,800s = 7days, hence the 6 days 23 hours remaining piece.

This is a local agent.

**Comment by i128** [comment]
Bug is with split on ': ' as mentioned above. Currently pulls -1 in the index, switching to slice (19...-1) since the output is always 19 chars :)

**Comment by i128** [comment]
eh scratch that, looks like column length is variable ...

**Comment by ccammilleri** [comment]
bah, the split is on ': ' so i didnt think this would happen...so hackerish of me. I got a better approach that will land in 0.7.3-beta

**Comment by i128** [comment]
This issue is already resolved in v0.7.3-beta (you'll need to upgrade your hashview/agents too if you're using them)
