### ISSUE TITLE
Request: Display current mask/attempt for bruteforce jobs

### ISSUE THREAD

**Issue by GrepItAll** [hashview/hashview#372]
It would be nice if the home screen showed what mask hashcat is currently using when attempting a bruteforce of a hash and/or what the command line input is that is causing it. I know you can see the command line input for upcoming jobs/chunks, but would be handy to see what currently is being processed

**Comment by i128** [comment]
![image](https://user-images.githubusercontent.com/2417131/33099603-060d3cc6-ced7-11e7-9ecb-c9cff01a208a.png)


Is this what you mean? i see it with my tests.

**Comment by GrepItAll** [comment]
Weird, I didn't think I saw that, but I might have just overlooked it somehow. I'll chuck another bruteforce job into my queue to test this again.

**Comment by i128** [comment]
I think the issue might be with the version of hashcat or drivers, the above is running an old version of hashcat, on my prod rig, Input.Mode. is shown as Guess.Mask. this is why you're probably not seeing it. Adding ability to detect/report on both.

**Comment by GrepItAll** [comment]
Great, thank you
