### ISSUE TITLE
Support $user:$hash:$salt

### ISSUE THREAD

**Issue by allwithfly** [hashview/hashview#373]
There are some salt encryption methods, need to crack together with the username.
How to support such a format?
thx
good job.

**Comment by i128** [comment]
Can you provide the specific hashcat hash type you're referring too, or interested in?

**Comment by allwithfly** [comment]
2611

**Comment by allwithfly** [comment]
2611

**Comment by GrepItAll** [comment]
2611 is a vBulletin format so from my understanding, hashcat expects an input of 'hash:salt'. Presumably your hash file is in the structure '$user:$hash:$salt'? If so, my pull request should enable support for this, although I assume it will come up as an unknown hash type.
