### ISSUE TITLE
I can't open my webpage! ERROR OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by tksjk20** [hashview/hashview#375]
## When I enter in the browser: 127.0.0.1:4567 the server logs:

[2017-11-24 03:29:20] ERROR OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=SSLv2/v3 read client hello A: http request
03:29:28 web.1               | 	/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/openssl/ssl.rb:290:in `accept'
03:29:28 web.1               | [2017-11-24 03:29:20] ERROR OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=SSLv2/v3 read client hello A: http request
03:29:28 web.1               | 	/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/openssl/ssl.rb:290:in `accept'
03:29:28 web.1               | [2017-11-24 03:29:20] ERROR OpenSSL::SSL::SSLError: SSL_accept returned=1 errno=0 state=SSLv2/v3 read client hello A: http request
03:29:28 web.1               | 	/usr/share/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/openssl/ssl.rb:290:in `accept'
03:29:28 web.1               | 127.0.0.1 - - [24/Nov/2017:03:29:22 -0600] "POST /v1/agents/9bca2200-34d6-47f1-8c74-ca883c7db7f3/heartbeat HTTP/1.1" 200 42 0.0140
# How can I solve this problem？

**Comment by GrepItAll** [comment]
As I mentioned in #369, you need to navigate to https://127.0.0.1:4567, not just 127.0.0.1:4567
