### ISSUE TITLE
My hashes has 150 million records，when visit /analytics show “Internal Server Error”

### ISSUE THREAD

**Issue by wfsunwj** [hashview/hashview#377]
The infos chucked into the console:
08:41:12 web.1               | 192.168.1.9 - - [27/Nov/2017:08:41:12 +0800] "GET /analytics HTTP/1.1" 500 30 342.5436
08:41:12 web.1               | 192.168.1.9 - - [27/Nov/2017:08:35:30 CST] "GET /analytics HTTP/1.1" 500 30

**Comment by i128** [comment]
Duplicate entry for issue  #376
