### ISSUE TITLE
when I "bundle install",I meet the problem

### ISSUE THREAD

**Issue by tksjk20** [hashview/hashview#378]
when I "bundle install",I meet the problem:
![image](https://user-images.githubusercontent.com/32348396/33261360-82b1cb00-d39d-11e7-953a-5d0c236ce6b2.png)
My OS is centOS.

**Comment by ccammilleri** [comment]
My guess is there is a mysql dev pacakage that is missing. Since we havent
tested on centos, im not sure what it would be named.
