### ISSUE TITLE
Internal server error when creating new user

### ISSUE THREAD

**Issue by antonio-marino** [hashview/hashview#385]
I recently installed hashview (using master branch), but I've have been getting an Internal Server Error whenever I try to add or edit a user. The beginning of the stack trace looks like this:

`18:43:45 web.1               | 2018-01-11 18:43:45 - NoMethodError - undefined method `auth_secret' for #<User:0x007f76200c10a0>:
18:43:45 web.1               |  /opt/hashview/routes/accounts.rb:62:in `block in <top (required)>'
18:43:45 web.1               |  /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
18:43:45 web.1               |  /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
18:43:45 web.1               |  /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
18:43:45 web.1               |  /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
18:43:45 web.1               |  /home/user/.rvm/gems/ruby-2.2.2/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
`
Any ideas on why this is happening?

**Comment by i128** [comment]
Confirmed, working on it now.

**Comment by i128** [comment]
Okay, its fixed in master. Unfortunately, since you've already did a db:setup, you'll need to do a quick manual alteration to a table that was missing the column

```
mysql -u <username> -p
# presuming you're using this in production
use hashview;
alter table users add column auth_secret varchar(50);
```

**Comment by antonio-marino** [comment]
That is not a problem! Thanks for the quick fix!
