### ISSUE TITLE
SMTP "Internal Server Error"

### ISSUE THREAD

**Issue by bzekanovic** [hashview/hashview#411]
Hashview Version 0.7.3
Getting "Internal Server Error" when trying to to test SMTP settings using "Send Test Email"
Server side error - "NoMethodError - undefined method `split' for nil:NilClass:"
SMTP Server - email.smtpserver.com:25
Sender Address - no-reply@domain.com
Use TLS = yes
SMTP Auth Type - none

**Comment by i128** [comment]
Did you save the settings before testing? What does the settings table look like in the database?
`use hashview`
`select * from settings;`

**Comment by bzekanovic** [comment]
Got this working with correct SMPT settings. 

Thanks,
