### ISSUE TITLE
CPU AND GPU Configuration

### ISSUE THREAD

**Issue by 007scorpio** [hashview/hashview#412]
Running the  application shows 0 cpu and 0 gpu. How do i make hashview see my cpu and gpu?

**Comment by i128** [comment]
What does `hashcat -I` show?

**Comment by 007scorpio** [comment]
hashcat (v4.0.1) starting...

/usr/bin/OpenCL/: No such file or directory

**Comment by 007scorpio** [comment]
am running on ubuntu 16.04

**Comment by GrepItAll** [comment]
Sounds like you're missing the OpenCL drivers/runtime. Check out https://hashcat.net/hashcat/ which lists what drivers are needed for what hardware near the top.

**Comment by i128** [comment]
@GrepItAll is correct you need to fix your installation of hashcat first before hashview can run properly.
