### ISSUE TITLE
Wrong password cracked

### ISSUE THREAD

**Issue by 007scorpio** [hashview/hashview#413]
AFter uploading my hashfile to hashview... the cracked hash is incorrect eg (NULL:1c3a0b25c3d1c909e2bcb9fe44c2f904:#!comment:)

**Comment by ccammilleri** [comment]
to confirm, this is a md4 hash?

**Comment by 007scorpio** [comment]
It MD5 Please 

Thank You

**Comment by ccammilleri** [comment]
bah, 4 is next to 5 on my keyboard ;-)

I'll load it in my rig and see what happens. did this hash crack via a job or was it detected as already previously cracked in the "local checks" screen when you were setting up the job?

**Comment by 007scorpio** [comment]
It was cracked via a job please and all gave wrong passwords.

**Comment by ccammilleri** [comment]
I'm sorry but I cant replicate this behavior. Please reopen if hashcat is providing different results than what is displayed in hashview.
