### ISSUE TITLE
 Running， but cannot be accessed

### ISSUE THREAD

**Issue by dd404x** [hashview/hashview#416]
![image](https://user-images.githubusercontent.com/19923974/40153191-1c6cc9c2-59bb-11e8-9805-d794273da6fb.png)
![image](https://user-images.githubusercontent.com/19923974/40153234-64a36052-59bb-11e8-8fc6-de8cca6daf66.png)
![image](https://user-images.githubusercontent.com/19923974/40153240-6e556276-59bb-11e8-9dbe-88571c27d07e.png)

**Comment by dd404x** [comment]
![image](https://user-images.githubusercontent.com/19923974/40153883-64affaa8-59be-11e8-9677-75b8bf1c0631.png)
![image](https://user-images.githubusercontent.com/19923974/40153897-741bed76-59be-11e8-9b64-f6e253ab6527.png)

**Comment by i128** [comment]
It looks like redis might already be running. Before starting hashview, make sure its turned off by:
`service stop redis`
You can verify via: 
`netstat -lntp | grep 4567`
Once its off, try again:
`RACK_ENV=production foreman start`

**Comment by dd404x** [comment]
@i128 thanks for your help.，My problem has been solved.
![image](https://user-images.githubusercontent.com/19923974/40168308-c1fff2e4-59f5-11e8-974f-7e5ecc507ceb.png)
You are a good man.
