### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by l0nax** [hashview/hashview#421]
I have tryed to install Hashview on Ubuntu Xenial; Debian Stretch; Debian Sid; Debian Jessie

On all operating Systems the Project **can not** create the Database Input **and** can **NOT** start

**Comment by HugoPouliquen** [comment]
Hello
Can you put your traces and your commands? I succeeded to install it on Xenial

**Comment by ccammilleri** [comment]
Please provide more information so we can help. As of right now the only issue that is known is related to installation relates to the digest gem. #419
