### ISSUE TITLE
Failed Fetching Digest 0.0.1

### ISSUE THREAD

**Issue by antman1p** [hashview/hashview#434]
I am trying to install hashview according to your instructions.  When I run 'bundle install' It fails at 'Fetching digest 0.0.1.'  I am using the master branch.  When i switch to the beta 7.4 branch I do not have this issue, but hashview fails at run with that branch due to a syntax error "hashfiles.rb:21: syntax error, unexpected '.'", so I came back  to the Master branch and can't get past this error:

Gem::RemoteFetcher::FetchError: bad response Forbidden 403 (https://rubygems.org/gems/digest-0.0.1.gem)
An error occured while installing digest (0.0.1), and Bundler cannot continue.

**Comment by HugoPouliquen** [comment]
Hello @antman1p 

Could you... 
1 - Remove your db with `RACK_ENV=production bundle exec rake db:destroy`? 
2 - Remove hasview folder
3 - Clone hashview 
4 - Git checkout on `v0.7.4-beta` 
5 - Launch `RACK_ENV=production bundle exec rake db:setup` 

and tell me if you have one more bug.

**Comment by antman1p** [comment]
I found that if I comment out #digest in the Gemfile, the rest of the bundle installs.  I was then able to start the server and connect, but I was getting an internal server error when I tried to create new jobs.

I just did what you said above and am still getting the syntax error:
/home/<redacted>/hashview/routes/init.rb:7:in 'require_relative': /home/<redacted>/hashview/routes/hashfiles.rb:21: syntax error, expected '.' (SyntaxError)
     hash_id = hashfilehash&.hash_id.to_s || 'hash id error'
                                             ^

**Comment by HugoPouliquen** [comment]
What is your Ruby version?

**Comment by antman1p** [comment]
2.2.2p95

**Comment by HugoPouliquen** [comment]
Hashview Ruby version is 2.4.4: https://github.com/hashview/hashview/blob/v0.7.4-beta/.ruby-version

So try with this :)

**Comment by antman1p** [comment]
How do I properly change/update/install this version without breaking everything?  My experiences with Ruby have been Pretty.... Well, VERY BAD.

**Comment by i128** [comment]
We should just remove it from the master from now until we can land v0.7.4-beta

**Comment by antman1p** [comment]
Problem is that this may be causing the internal server error that I a m getting?

**Comment by HugoPouliquen** [comment]
This syntax: `hashfilehash&.hash_id.to_s` is only available with Ruby 2.3+ and you have Ruby 2.2.2 so it's normal that you've a problem

**Comment by antman1p** [comment]
unfortunately I already did rvm upgrade 2.2.2 2.4.4

waiting for it to end to see if everything works

**Comment by i128** [comment]
so the internal error is probably due to a different set of Gems  and ruby versions between v0.7.4-beta and master.

After getting to 2.4.4 do a `bundle install`

**Comment by i128** [comment]
That said since v0.7.4 is still in dev... there may situations where its not stable.

**Comment by antman1p** [comment]
The upgrade failed.

**Comment by antman1p** [comment]
@i128 I had the internal server error when I used the Master branch and commented out 'digest' in the Gemfile, not using the beta branch

**Comment by antman1p** [comment]
OK, I did "bundle install" on this beta branch.  Should I run hashview now?

**Comment by i128** [comment]
after bundle install is run, continue with 
step 5: `RACK_ENV=production bundle exec rake db:setup`

**Comment by i128** [comment]
then continue from the instructions here:
https://github.com/hashview/hashview/wiki/01-Installing-Hashview

**Comment by i128** [comment]
Okay so master should be fixed? maybe? if you want to use that just go back to master, and try going through the install process referenced in the wiki

**Comment by antman1p** [comment]
It worked.  I am able to create a job as well thanks!
I'm not sure what you guys can do about the Master though.  If oyu comment out the digest the bundle installs, but I could not create a job.

**Comment by HugoPouliquen** [comment]
Great! In the new versions of Ruby, Digest is [already include in stlib](https://ruby-doc.org/stdlib-2.4.4/libdoc/digest/rdoc/Digest.html). So, when the beta branch merge on master this problem will be solved. 

If everything's ok, could you close your issue?

**Comment by antman1p** [comment]
Everything seems to be working fine.  Thank you.

**Comment by HugoPouliquen** [comment]
@i128 if you want, you can close this issue
