### ISSUE TITLE
Hashview wont start 

### ISSUE THREAD

**Issue by Mockedarche** [hashview/hashview#450]
Followed everything from the guide have everything set up but when I launch via RACK_ENV=production TZ='America/Denver' foreman start I get 
RACK_ENV=production TZ='America/Denver' foreman start
04:11:40 redis.1             | started with pid 10439
04:11:40 mgmt-worker.1       | started with pid 10440
04:11:40 hashcat-worker.1    | started with pid 10441
04:11:40 background-worker.1 | started with pid 10443
04:11:40 web.1               | started with pid 10445
04:11:40 redis.1             | 10439:C 21 Oct 04:11:40.957 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
04:11:40 redis.1             | 10439:C 21 Oct 04:11:40.957 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=10439, just started
04:11:40 redis.1             | 10439:C 21 Oct 04:11:40.957 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.958 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.958 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.958 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.959 * Running mode=standalone, port=6379.
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.959 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.959 # Server initialized
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.959 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.959 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.959 * DB loaded from disk: 0.000 seconds
04:11:40 redis.1             | 10439:M 21 Oct 04:11:40.959 * Ready to accept connections
04:11:41 web.1               | /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/adapters/mysql.rb:109:in `real_connect': Mysql::Error: Access denied for user 'root'@'localhost' (Sequel::DatabaseConnectionError)
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/adapters/mysql.rb:109:in `connect'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool.rb:116:in `make_new'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:228:in `make_new'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:201:in `available'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:137:in `_acquire'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:151:in `block in acquire'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:282:in `block in sync'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:282:in `synchronize'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:282:in `sync'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:150:in `acquire'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:106:in `hold'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/database/connecting.rb:301:in `synchronize'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/database/transactions.rb:165:in `transaction'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/model/base.rb:1003:in `check_non_connection_error'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/model/base.rb:1125:in `get_db_schema'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/model/base.rb:894:in `set_dataset'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/model/base.rb:219:in `Model'
04:11:41 web.1               | 	from /home/austin/.rvm/gems/ruby-2.2.2/gems/sequel-4.48.0/lib/sequel/model/base.rb:164:in `block in def_Model'
04:11:41 web.1               | 	from /home/austin/hashview/models/master.rb:31:in `<top (required)>'
04:11:41 web.1               | 	from ./hashview.rb:9:in `require_relative'
04:11:41 web.1               | 	from ./hashview.rb:9:in `<main>'
04:11:41 background-worker.1 | resque-scheduler: [INFO] 2018-10-21T04:11:41-06:00: Starting
04:11:41 background-worker.1 | resque-scheduler: [INFO] 2018-10-21T04:11:41-06:00: Loading Schedule
04:11:41 background-worker.1 | resque-scheduler: [INFO] 2018-10-21T04:11:41-06:00: Scheduling do_wordlist_importer 
04:11:41 background-worker.1 | resque-scheduler: [INFO] 2018-10-21T04:11:41-06:00: Scheduling do_rulelist_importer 
04:11:41 background-worker.1 | resque-scheduler: [INFO] 2018-10-21T04:11:41-06:00: Scheduling do_cleanUp 
04:11:41 background-worker.1 | resque-scheduler: [INFO] 2018-10-21T04:11:41-06:00: Schedules Loaded
04:11:42 web.1               | exited with code 1
04:11:42 system              | sending SIGTERM to all processes
04:11:42 redis.1             | 10439:signal-handler (1540116702) Received SIGTERM scheduling shutdown...
04:11:42 redis.1             | 10439:M 21 Oct 04:11:42.062 # User requested shutdown...
04:11:42 redis.1             | 10439:M 21 Oct 04:11:42.062 * Saving the final RDB snapshot before exiting.
04:11:42 redis.1             | 10439:M 21 Oct 04:11:42.065 * DB saved on disk
04:11:42 redis.1             | 10439:M 21 Oct 04:11:42.065 # Redis is now ready to exit, bye bye...
04:11:42 redis.1             | exited with code 0
04:11:42 mgmt-worker.1       | terminated by SIGTERM
04:11:42 hashcat-worker.1    | terminated by SIGTERM
04:11:42 background-worker.1 | terminated by SIGTERM
Any help would be appreciated (if this isn't the correct area to post this just tell me and ill removed it)

**Comment by HugoPouliquen** [comment]
Hello guy,
You have an error in your config:  `Mysql::Error: Access denied for user 'root'@'localhost' (Sequel::DatabaseConnectionError)`. Check your `confi/database.yml`

**Comment by HugoPouliquen** [comment]
Hello guy,
You have an error: `Mysql::Error: Access denied for user 'root'@'localhost' (Sequel::DatabaseConnectionError)`. Check you `config/database.yml` and your DB rights
