### ISSUE TITLE
Kali OS (not VM) Hashcat/GPU issue

### ISSUE THREAD

**Issue by soronrheeyi** [hashview/hashview#451]
Hi all,

I am new to running Kali as my primary OS. I'm following these instructions to try my hand at getting the wifi password to my own personal network: https://www.wikihow.com/Hack-WPA/WPA2-Wi-Fi-with-Kali-Linux

Everything goes smoothly until I get to the bit where I run HASH_FILE=name.hccapx POT_FILE=name.pot HASH_TYPE=2500 ./naive-hashcat.sh

At which point I get this error:
Not a native Intel OpenCL runtime. Expect massive speed loss. You can use --force to override, but do not report related errors.

At which point the program stops and I am presented with the command prompt.

I've researched my system's processor and this is what I have: https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/atom-z36xxx-z37xxx-datasheet-vol-1.pdf

From what I can conclude, my graphics card does support OpenCL. I am wondering what I am missing. Thoughts?

**Comment by GrepItAll** [comment]
Ok, so firstly your issues are not related to Hashview, this is a driver misconfiguration situation. You can try appending "--force" to the command line as prompted, but that behaviour can be buggy.

Otherwise, make sure you download the latest OpenCL Runtime. Check the Hashcat website for info

**Comment by GrepItAll** [comment]
Also, just use Hashcat, don't use an out of date wrapper (like naive-hashcat)

**Comment by i128** [comment]
@GrepItAll is correct. Hashcat needs to be functional outside of hashview in order to work. Try running a hashcat -b (benchmark) to make sure its working first.

**Comment by GrepItAll** [comment]
Looks like the @soronrheeyi has created an issue over at https://github.com/hashcat/hashcat/issues/1731 so this can probably be closed?
