### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gs135269** [hashview/hashview#458]
I just configured the new ubuntu16.04 system, after the configuration is complete, the main page of the hashview can be accessed, or the task can be created (but it can't be executed and always queued), but when you go to the Tasks Groups page, you will be prompted with the error Internal. Server Error, there are many also pages that will prompt such errors. I want to know if you have encountered such a problem and how to solve it? I know this is a simple question, but I don't know anything about ubuntu's website. please help me. .

**Comment by i128** [comment]
Is this a fresh Install or upgrade? can you provide the output of what you see in the console?

**Comment by i128** [comment]
sorry for the late reply, is the value of the PATH set within config/agent_config.json?

**Comment by ccammilleri** [comment]
let us know if you're still having problems

**Comment by sodian** [comment]
hello,if you have solve this problem?

**Comment by ccammilleri** [comment]
What problem are you having and do you have any logs that I can look at? also, what OS are you running on?
