### ISSUE TITLE
What size storage is recommended?

### ISSUE THREAD

**Issue by jjmoody** [hashview/hashview#470]
Correct me if I’m wrong, but when I upload a very large dictionary file (aprox 1 TB+) I assume the file is saved in the MySQL database. If so, what size HD is recommended for the master hashview rig? I also assume this only applies to the master and not the clients in a multi-rig setup. 

Please share your knowledge & experience on the topic. Thanks!

**Comment by ccammilleri** [comment]
@jjmoody I usually recommend at least a 1tb for your exact reason: to support large wordlists.

But the answer depends solely on how large your wordlist collections are. Hashview stores just the file on the master and does not store the words in the database, just metadata about the wordlist (word count, filepath, etc.)

Agents check into the master, and if they don't have a copy of the wordlist, they obtain it from the master, so agents should have similar disk size requirements.

Hope this helps!
