### ISSUE TITLE
Best way to restore to new HD

### ISSUE THREAD

**Issue by khatfull** [hashview/hashview#477]
Think we have an SSD that's getting flaky.  Checking the CHANGELOG.md it looks like we're on v0.7.3-beta 2018-01-10.  What's the best way to move the existing installation and data?  Clean install, restore backup from old?  Move the install somehow?  Also thought of cloning the drive if it seems to read OK as opposed to write.  Thanks for any help.

**Comment by i128** [comment]
You should be able to do the following:

first, perform a sqldump of the existing DB on your current system and save it to file. This will essentially backup your entire hashview db. 

`mysqldump -u root --password hashview > {{filename.sql}}`

Then on your new system, set it up as you would normally, but when done, move your sqldump file over, and import it into the new db. 

`mysql -u root --password hashview < {{filename.sql}}`

Make sure hashview is stopped both before exporting and importing and you should be good to go.
