### ISSUE TITLE
Adding Hash Types

### ISSUE THREAD

**Issue by CryptoAssetRecovery** [hashview/hashview#63]
Hello, can anyone point me in the right direction for where to add hash types that are not automatically supported?

**Comment by i128** [comment]
No real good place at the moment, so place them here for now!

**Comment by CryptoAssetRecovery** [comment]
Thank you kindly! 

The primary hashes we use are:

15200 Blockchain, My Wallet, V2
18800 Blockchain, My Wallet, Second Password (SHA256)
12700 Blockchain, My Wallet
22500 MultiBit Classic .key (MD5)
11300 Bitcoin/Litecoin wallet.dat
16300 Ethereum Pre-Sale Wallet, PBKDF2-HMAC-SHA256
15600 Ethereum Wallet, PBKDF2-HMAC-SHA256
15700 Ethereum Wallet, SCRYPT
22700 MultiBit HD (scrypt)

**Comment by CryptoAssetRecovery** [comment]
I sorted it myself, thank you anyway!

**Comment by peonsra** [comment]
Can you share how you were able to add new hash types? It appears that I can only choose from 16 different hash types when creating a new job.

**Comment by CryptoAssetRecovery** [comment]
Im sorry, I don't entirely remember but I can tell you the way I did it was just searching through python to find where those hash types were defined and then adding my own using the types already there as a temple. Its not too difficult to find.

**Comment by i128** [comment]
Modifications are made here:
https://github.com/hashview/hashview/blob/main/hashview/jobs/forms.py#L28

And thanks to a recent PR a bunch more have been added.
