### ISSUE TITLE
hashview.py: error: unrecognized arguments: ./hashview.py

### ISSUE THREAD

**Issue by lawrenceamer** [hashview/hashview#67]
it has been tested with 
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04

```
and python3.10, but seems not working

**Comment by lawrenceamer** [comment]
i tried to execute python3 ./hashview.py --debug and from the following path /home/user/hasview/ same results and same error msg

**Comment by i128** [comment]
did the setup.py execute successfully?

**Comment by lawrenceamer** [comment]
setup is successfully completed and still same error msg

**Comment by lawrenceamer** [comment]
@i128 i think there is such an error on setup.py 
![image](https://user-images.githubusercontent.com/10256911/172754095-13e681ef-20fe-436d-ad04-adb12272f822.png)
![image](https://user-images.githubusercontent.com/10256911/172754164-5ef4c0e7-ccea-415b-a32a-0505f2dfd6d9.png)

**Comment by lawrenceamer** [comment]
there is a kind of error while initiating the setup 
```
migrations/versions/32e2976dcda0_outboard_migration_handling.py", line 40, in upgrade
    with open('VERSION.TXT', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION.TXT'

```

**Comment by lawrenceamer** [comment]
I have created an empty VERSION.TXT file and it solved that setup error, after completing the setup, I still can't start the instance with same error

**Comment by lawrenceamer** [comment]
a kind of another error?
```

Please make sure that your dependencies are up to date (including replacing Flask-Bcrypt with Bcrypt-Flask).
Exception!:
Traceback (most recent call last):
  File "/home/user/hashview/./hashview.py", line 35, in ensure_flask_bcrypt
    raise Exception('old version')
Exception: old version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/hashview/./hashview.py", line 339, in cli
    ensure_flask_bcrypt()
  File "/home/user/hashview/./hashview.py", line 38, in ensure_flask_bcrypt
    exit(1)
  File "/usr/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
```

**Comment by lawrenceamer** [comment]
I have temporarily fixed the issue by modifying the code block, i am not sure why? but i am using the latest version of flask_bcrypt
```
def ensure_flask_bcrypt():
    try:
        import flask_bcrypt
#        if ('1.0.1' >=flask_bcrypt.__version__):
#            raise Exception('old version')
    except:
        print('\nPlease make sure that your dependencies are up to date (including replacing Flask-Bcrypt with Bcrypt-Flask).')
#        exit(1)

```

**Comment by i128** [comment]
The missing VERSION.TXT requirement was just addressed today, so you should be able to git pull that for that fix. (it might require blowing away the hashview db first). You can also just leave a dummy VERSION.TXT file for the time being, no harm in that.

As for flask-bcrypt, I've run into that issue intermittently. One suggestion would be to try `pip install -r requirements --upgrade`. This forces all modules to upgrade to the latest version.

**Comment by pingywon** [comment]
I am getting a different error:

`usage: hashview.py [-h] [--debug] [--no-ssl]
hashview.py: error: unrecognized arguments: ./hashview.py
Exception!:
Traceback (most recent call last):
  File "/home/pingywon/hashview/./hashview.py", line 333, in cli
    args = parser.parse_args(args)
  File "/usr/lib/python3.9/argparse.py", line 1833, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3.9/argparse.py", line 2587, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.9/argparse.py", line 2574, in exit
    _sys.exit(status)
SystemExit: 2`

Running Debian with everything up today.

**Comment by FreeZeroDays** [comment]
> I am getting a different error:
> 
> `usage: hashview.py [-h] [--debug] [--no-ssl] hashview.py: error: unrecognized arguments: ./hashview.py Exception!: Traceback (most recent call last): File "/home/pingywon/hashview/./hashview.py", line 333, in cli args = parser.parse_args(args) File "/usr/lib/python3.9/argparse.py", line 1833, in parse_args self.error(msg % ' '.join(argv)) File "/usr/lib/python3.9/argparse.py", line 2587, in error self.exit(2, _('%(prog)s: error: %(message)s\n') % args) File "/usr/lib/python3.9/argparse.py", line 2574, in exit _sys.exit(status) SystemExit: 2`
> 
> Running Debian with everything up today.

I am running into this same issue on a fresh Ubuntu installation. Setup appears to complete fine but running hashview.py results in the error.

**Comment by i128** [comment]
@pingywon  what switches are you passing if any? I just ran through the install last night and didnt get that message. i dont _THINK_ it should matter, but what happens if you try with python 3.8.10?

**Comment by pingywon** [comment]
> @pingywon what switches are you passing if any? I just ran through the install last night and didnt get that message. i dont _THINK_ it should matter, but what happens if you try with python 3.8.10?

I have tried no switches and —debug same result. Currently away from the machine

**Comment by i128** [comment]
Okay did a fresh install with ubuntu 22.04 and python3.10.4 and encountered the same issue. all dev/testing was done on Ubuntu 20.04 Python 3.8. going to see what changes need to be made to support the newer versions.

**Comment by i128** [comment]
okay, identified the _cause_ of the error. Do a git/pull and try again. You shouldnt need to re-run ./setup.py.   just ./hashview.py
